// Utilities3.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities3
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct Drawable { void (*unscheduleDrawable)(void*,Drawable*,Runnable*); } Drawable;
        */

        /*
typedef struct Drawable_Callback { void (*unscheduleDrawable)(void*,Drawable*,Runnable*); void (*invalidateDrawable)(void*,Drawable*); void (*scheduleDrawable)(void*,Drawable*,Runnable*,long); } Drawable_Callback;
        */

        /*
typedef struct b_c { void (*p)(void*); } b_c;
        */

        /*
typedef struct c { void (*setVisible)(void*,boolean,boolean); boolean (*getCallback)(void*); } c;
        */

        /*
typedef struct d_a { Drawable* newDrawable(void*); Drawable* newDrawable(void*,Resources*); } d_a;
        */

        /*
typedef struct a { MenuItem* setCheckable(void*,boolean); uint* t; } a;
        */

        // Original: unscheduleDrawable
        public static void UnscheduleDrawable(b_b menuItem, Drawable isCheckable, Runnable runnable)
        {
            Drawable_Callback drawable = menuItem.f;
            if (drawable != null)
            {
                drawable.UnscheduleDrawable(isCheckable, runnable);
            }
        }

        // Original: setVisible
        public static bool setVisible(MenuItem menuItem, bool isCheckable, bool runnable)
        {
            bool isVisible;
            Drawable drawable;
        
            isVisible = base.setVisible(menuItem, isCheckable, runnable);
        
            drawable = menuItem.drawable1;
            if (drawable != null)
            {
                drawable.setVisible(isCheckable, runnable);
            }
        
            drawable = menuItem.drawable2;
            if (drawable != null)
            {
                drawable.setVisible(isCheckable, runnable);
            }
        
            return isVisible;
        }

        // Original: invalidateDrawable
        public static void InvalidateDrawable(b menuItem, Drawable isCheckable)
        {
            b_c drawable = *menuItem.f;
            if (drawable != null)
            {
                drawable.invalidate();
            }
        
            if ((isCheckable == *menuItem.h) && (*menuItem.getCallback() != null))
            {
                Drawable_Callback callback = *menuItem.getCallback();
                callback.invalidateDrawable(callback, menuItem);
            }
        }

        // Original: scheduleDrawable
        public static void ScheduleDrawable(b menuItem, Drawable isCheckable, Runnable runnable, long delay)
        {
            if (isCheckable == menuItem.h && menuItem.getCallback() != null)
            {
                Drawable_Callback callback = menuItem.getCallback();
                callback.scheduleDrawable(callback, menuItem, runnable, delay);
            }
        }

        // Original: unscheduleDrawable
        public static void UnscheduleDrawable(b menuItem, Drawable isCheckable, Runnable runnable)
        {
            if (isCheckable == menuItem.h && menuItem.getCallback() != null)
            {
                Drawable_Callback callback = menuItem.getCallback();
                callback.unscheduleDrawable(callback, menuItem, runnable);
            }
        }

        // Original: setVisible
        public static bool setVisible(c menuItem, bool isCheckable, bool runnable)
        {
            bool isVisible;
            Drawable drawable;
        
            isVisible = base.setVisible(menuItem, isCheckable, runnable);
            if (isVisible || (drawable = menuItem.f, isVisible = drawable.setVisible(drawable, isCheckable, runnable), isVisible))
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        // Original: invalidateDrawable
        public static void InvalidateDrawable(Drawable drawable)
        {
            drawable.InvalidateSelf();
        }

        // Original: scheduleDrawable
        public static void ScheduleDrawable(Drawable menuItem, Runnable runnable, long delay)
        {
            ((Drawable.Callback)menuItem).ScheduleSelf(menuItem, runnable, delay);
        }

        // Original: unscheduleDrawable
        public static void UnscheduleDrawable(Drawable menuItem, Runnable runnable)
        {
            ((Drawable.Callback)menuItem).UnscheduleSelf(runnable);
        }

        // Original: newDrawable
        public static Drawable newDrawable(D_a menuItem)
        {
            Drawable drawable;
            drawable = new d(menuItem, (Resources)0x0);
            return drawable;
        }

        // Original: newDrawable
        public static Drawable NewDrawable(d_a menuItem, Resources isCheckable)
        {
            d drawable = new d(menuItem, isCheckable);
            return drawable;
        }

        // Original: setCheckable
        public static MenuItem SetCheckable(MenuItem menuItem, bool isCheckable)
        {
            menuItem.t = (byte)(isCheckable ? 1 : 0) | (menuItem.t & 0xFFFFFFFE);
            return menuItem;
        }

    }
}
