// Utilities8.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities8
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct d { void (*b)(d*); } d;
        */

        /*
typedef struct s { void (*b)(s*); } s;
        */

        /*
typedef struct l { void (*b)(l*); } l;
        */

        // Original: setCheckMarkDrawable
        public static void SetCheckMarkDrawable(f appCompatRadioButton, int drawable)
        {
            Context context = appCompatRadioButton.getContext();
            Drawable drawableResource = a_d(context, drawable);
            appCompatRadioButton.setCheckMarkDrawable(drawableResource);
        }

        // Original: drawableStateChanged
        public class AppCompatEditText : EditText, IViewTreeObserverOnDrawListener
        {
            protected override void OnDrawableStateChanged(int[] state)
            {
                base.OnDrawableStateChanged(state);
        
                var drawableStateListener1 = f;
                if (drawableStateListener1 != null)
                {
                    drawableStateListener1.b();
                }
        
                var drawableStateListener2 = g;
                if (drawableStateListener2 != null)
                {
                    drawableStateListener2.b();
                }
            }
        }

        // Original: setBackgroundDrawable
        public static void SetBackgroundDrawable(EditText editText, Drawable drawable)
        {
            ((android.widget.EditText)editText).setBackgroundDrawable(drawable);
            var drawableStateListener = (d)editText.f;
            if (drawableStateListener != null)
            {
                drawableStateListener.f(drawableStateListener, drawable);
            }
        }

        // Original: drawableStateChanged
        public static void DrawableStateChanged(k appCompatRadioButton)
        {
            d drawableStateListener;
        
            base.DrawableStateChanged(appCompatRadioButton);
            drawableStateListener = appCompatRadioButton.f;
            if (drawableStateListener != null)
            {
                drawableStateListener.b(drawableStateListener);
            }
            drawableStateListener = appCompatRadioButton.g;
            if (drawableStateListener != null)
            {
                drawableStateListener.b(drawableStateListener);
            }
        }

        // Original: setBackgroundDrawable
        public static void SetBackgroundDrawable(android.widget.ImageButton appCompatRadioButton, android.graphics.drawable.Drawable drawable)
        {
            d drawableStateListener = appCompatRadioButton.f;
        
            appCompatRadioButton.setBackgroundDrawable(drawable);
        
            if (drawableStateListener != null)
            {
                drawableStateListener.f(drawableStateListener, drawable);
            }
        }

        // Original: setImageDrawable
        public static void setImageDrawable(k appCompatRadioButton, Drawable drawable)
        {
            l drawableStateListener = appCompatRadioButton.g;
        
            if (drawableStateListener != null)
            {
                drawableStateListener.b();
            }
        
            ((android.widget.ImageButton)appCompatRadioButton).setImageDrawable(drawable);
        }

        // Original: drawableStateChanged
        public static void drawableStateChanged(AppCompatImageView appCompatRadioButton)
        {
            d drawableStateListener;
        
            base.drawableStateChanged(appCompatRadioButton);
            drawableStateListener = appCompatRadioButton.f;
            if (drawableStateListener != null)
            {
                drawableStateListener.b(drawableStateListener);
            }
            drawableStateListener = appCompatRadioButton.g;
            if (drawableStateListener != null)
            {
                drawableStateListener.b(drawableStateListener);
            }
        }

        // Original: setBackgroundDrawable
        public static void SetBackgroundDrawable(AppCompatImageView appCompatRadioButton, Drawable drawable)
        {
            d drawableStateListener = appCompatRadioButton.f;
        
            appCompatRadioButton.setBackgroundDrawable(drawable);
        
            if (drawableStateListener != null)
            {
                drawableStateListener.f(drawableStateListener, drawable);
            }
        }

        // Original: setImageDrawable
        public static void setImageDrawable(AppCompatImageView appCompatRadioButton, Drawable drawable)
        {
            IAppCompatDrawableStateListener drawableStateListener = appCompatRadioButton.drawableStateListener;
        
            appCompatRadioButton.setImageDrawable(drawable);
        
            if (drawableStateListener != null)
            {
                drawableStateListener.onDrawableStateChanged();
            }
        }

        // Original: drawableStateChanged
        public static void DrawableStateChanged(MultiAutoCompleteTextView appCompatRadioButton)
        {
            d drawableStateListener;
        
            base.DrawableStateChanged(appCompatRadioButton);
            drawableStateListener = appCompatRadioButton.g;
            if (drawableStateListener != null)
            {
                drawableStateListener.b(drawableStateListener);
            }
            drawableStateListener = appCompatRadioButton.h;
            if (drawableStateListener != null)
            {
                drawableStateListener.b(drawableStateListener);
            }
        }

        // Original: setBackgroundDrawable
        public static void SetBackgroundDrawable(m appCompatRadioButton, Drawable drawable)
        {
            d drawableStateListener = appCompatRadioButton.g;
            if (drawableStateListener != null)
            {
                drawableStateListener.f(drawable);
            }
        
            ((MultiAutoCompleteTextView)appCompatRadioButton).setBackgroundDrawable(drawable);
        }

        // Original: drawableStateChanged
        public static void DrawableStateChanged(AppCompatRadioButton appCompatRadioButton)
        {
            d drawableStateListener;
        
            base.DrawableStateChanged(appCompatRadioButton);
            drawableStateListener = appCompatRadioButton.g;
            if (drawableStateListener != null)
            {
                drawableStateListener.b(drawableStateListener);
            }
            drawableStateListener = appCompatRadioButton.h;
            if (drawableStateListener != null)
            {
                drawableStateListener.b(drawableStateListener);
            }
        }

    }
}
