// Utilities9.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities9
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct d { void (*f)(void*, Drawable*); } d;
        */

        /*
typedef struct g { void (*f)(void*); } g;
        */

        // Original: setBackgroundDrawable
        public static void SetBackgroundDrawable(AppCompatRadioButton seekBar, Drawable drawableId)
        {
            Drawable drawableRef = seekBar.g;
        
            if (drawableRef != null)
            {
                drawableRef.f(drawableId);
            }
        
            base.SetBackgroundDrawable(seekBar, drawableId);
        }

        // Original: setButtonDrawable
        public static void SetButtonDrawable(AppCompatRadioButton seekBar, Drawable drawableId)
        {
            seekBar.SetButtonDrawable(drawableId);
            var drawableRef = seekBar.f;
            if (drawableRef != null)
            {
                drawableRef.Dispose();
            }
        }

        // Original: setButtonDrawable
        public static void SetButtonDrawable(AppCompatRadioButton seekBar, int drawableId)
        {
            Context context = seekBar.GetContext();
            Drawable drawable = a_d(context, drawableId);
            seekBar.SetButtonDrawable(drawable);
        }

        // Original: drawableStateChanged
        public class SeekBar : SeekBar
        {
            protected override void OnDrawableStateChanged(int[] state)
            {
                base.OnDrawableStateChanged(state);
                var drawable = GetDrawable();
                if (drawable != null)
                {
                    drawable.State = state;
                }
            }
        }

    }
}
