// Utilities5.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities5
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct b { void (*setCheckable)(b*, boolean); void (*setEnabled)(b*, boolean); MenuItem* (*setVisible)(b*, boolean); boolean (*isCheckable)(b*); boolean (*isEnabled)(b*); } b;
        */

        /*
typedef struct i { uint *y; int *n; int *B; } i;
        */

        /*
typedef struct g { ArrayList **g; void (*M)(g*, boolean); void (*L)(g*, MenuItem*); } g;
        */

        /*
typedef struct MenuItemImpl { uint *y; int *n; b **d; } MenuItemImpl;
        */

        // Original: setGroupVisible
        public static void SetGroupVisible(g menuItem, int visible)
        {
            bool isEnabledResult = false;
            int groupCount = menuItem.g.Count;
        
            for (int groupIndex = 0; groupIndex < groupCount; groupIndex++)
            {
                g currentMenuItem = menuItem.g[groupIndex];
                int groupId = currentMenuItem.getGroupId();
        
                if (groupId == visible && currentMenuItem.y(visible))
                {
                    isEnabledResult = true;
                }
            }
        
            if (isEnabledResult)
            {
                menuItem.M(true);
            }
        }

        // Original: setCheckable
        public static uint setCheckable(MenuItem menuItem, bool visible)
        {
            uint currentFlags = *(uint*)menuItem.y;
            uint newCheckableFlag = (uint)visible | (currentFlags & 0xfffffffe);
            *(uint*)menuItem.y = newCheckableFlag;
        
            if (currentFlags != newCheckableFlag)
            {
                g menuItemRef = *(g*)menuItem.n;
                menuItemRef.M(menuItemRef, false);
            }
        
            return newCheckableFlag;
        }

        // Original: setEnabled
        public static MenuItem setEnabled(MenuItem menuItem, bool visible)
        {
            int flags = menuItem.y;
        
            if (visible)
            {
                flags |= 0x10;
            }
            else
            {
                flags &= 0xffffffef;
            }
        
            menuItem.y = flags;
            menuItem.n.M(menuItem, false);
        
            return menuItem;
        }

        // Original: setVisible
        public static MenuItem setVisible(MenuItem menuItem, bool visible)
        {
            bool isEnabledResult;
            g* menuItemRef;
        
            isEnabledResult = menuItem.y(menuItem, visible);
            if (isEnabledResult)
            {
                menuItemRef = *menuItem.n;
                menuItemRef.L(menuItemRef, menuItem);
            }
            return menuItem;
        }

        // Original: isCheckable
        public static bool IsCheckable(ref MenuItem menuItem)
        {
            return (menuItem.y & 1U) == 1;
        }

        // Original: isEnabled
        public static bool isEnabled(int menuItem)
        {
            return (menuItem & 0x10U) != 0;
        }

        // Original: isVisible
        public static bool IsVisible(ref MenuItem menuItem)
        {
            if (menuItem == null)
                return true;
        
            bool isEnabled = menuItem.IsEnabled();
            if (!isEnabled)
                return false;
        
            if ((menuItem.Flags & 8) != 0)
                return false;
        
            menuItem = menuItem.Parent;
            isEnabled = menuItem?.IsEnabled() ?? true;
            return isEnabled && (menuItem?.Flags & 8) == 0;
        }

        // Original: setCheckable
        public static MenuItem SetCheckable(MenuItem menuItem, bool visible)
        {
            var menu = (b)menuItem.d;
            menu.setCheckable(visible);
            return menuItem;
        }

        // Original: setEnabled
        public static MenuItem setEnabled(MenuItem menuItem, bool visible)
        {
            var menu = (b)menuItem.d;
            menu.setEnabled(visible);
            return menuItem;
        }

        // Original: setVisible
        public static MenuItem setVisible(MenuItem menuItem, bool visible)
        {
            b menuImpl = (b)menuItem.d;
            menuImpl.setVisible(menuItem, visible);
            return menuItem;
        }

        // Original: isCheckable
        public static bool IsCheckable(ref IntPtr menuItem)
        {
            b menuItemObject = (b)menuItem;
            return menuItemObject.isCheckable(menuItemObject);
        }

        // Original: isEnabled
        public static bool IsEnabled(ref MenuItem menuItem)
        {
            bool isEnabledResult;
            b* menuItemPtr = (b*)menuItem.d;
            isEnabledResult = menuItemPtr->isEnabled(menuItemPtr);
            return isEnabledResult;
        }

    }
}
