// Utilities4.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities4
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct i { int m; boolean isChecked; void (*setChecked)(RadioButton*, boolean); int getVisibility(RadioButton*); void (*setVisibility)(RadioButton*, int); } i;
        */

        /*
typedef struct ListMenuItemView { RadioButton *h; CheckBox *j; i **f; void (*g)(ListMenuItemView*); void (*c)(ListMenuItemView*); ImageView *m; ImageView *l; } ListMenuItemView;
        */

        /*
typedef struct g { boolean A; int (*size)(g*); Object *(*get)(ArrayList*, int); void (*setGroupCheckable)(g*, int, boolean, boolean); void (*setGroupDividerEnabled)(g*, boolean); boolean z; } g;
        */

        // Original: setEnabled
        public static void setEnabled(MenuItem menuBuilder, bool groupId)
        {
            uint visibleFlag = groupId ? 0x10 : 0;
            menuBuilder.t = (uint)(visibleFlag | (menuBuilder.t & 0xffffffefU));
        }

        // Original: setVisible
        public static MenuItem setVisible(MenuItem menuBuilder, bool groupId)
        {
            uint visibleFlag = 8;
            if (groupId)
            {
                visibleFlag = 0;
            }
            menuBuilder.t &= 8U;
            menuBuilder.t |= visibleFlag;
            return menuBuilder;
        }

        // Original: isCheckable
        public static bool IsCheckable(ActionMenuItem menuBuilder)
        {
            return (menuBuilder.t & 1U) != 0;
        }

        // Original: isEnabled
        public static bool isEnabled(ActionMenuItem menuBuilder)
        {
            return (menuBuilder.t & 0x10U) != 0;
        }

        // Original: isVisible
        public static bool isVisible(ActionMenuItem menuBuilder)
        {
            return (menuBuilder.t & 8U) == 0;
        }

        // Original: setCheckable
        public static void setCheckable(ListMenuItemView menuBuilder, bool groupId)
        {
            if (!groupId && (menuBuilder.radio == null && menuBuilder.checkBox == null))
                return;
        
            var menuItemsAdapter = menuBuilder.menuItemsAdapter;
            bool isVisibleItem = menuItemsAdapter.isVisible();
        
            RadioButton radioButton = isVisibleItem ? menuBuilder.radio : menuBuilder.checkBox;
            CheckBox checkBox = isVisibleItem ? menuBuilder.checkBox : menuBuilder.radio;
        
            if (groupId)
            {
                bool isChecked = menuItemsAdapter.isChecked();
                radioButton.setChecked(isChecked);
                int visibility = radioButton.getVisibility();
                if (visibility != 0)
                    radioButton.setVisibility(0);
        
                if (checkBox != null && checkBox.getVisibility() != 8)
                    checkBox.setVisibility(8);
            }
            else
            {
                if (checkBox != null)
                    checkBox.setVisibility(8);
                if (radioButton != null)
                    radioButton.setVisibility(8);
            }
        }

        // Original: setGroupDividerEnabled
        public static void SetGroupDividerEnabled(ListMenuItemView menuBuilder, bool groupId)
        {
            ImageView menuItems;
        
            menuItems = menuBuilder.m;
            if (menuItems != null)
            {
                int groupCount = groupId && !menuBuilder.t ? 0 : 8;
                menuItems.setVisibility(groupCount);
            }
        }

        // Original: setSubMenuArrowVisible
        public static void SetSubMenuArrowVisible(ListMenuItemView menuBuilder, bool groupId)
        {
            ImageView menuItems;
            int groupCount;
        
            menuItems = menuBuilder.l;
            if (menuItems != null)
            {
                groupCount = groupId ? 0 : 8;
                menuItems.setVisibility(groupCount);
            }
        }

        // Original: hasVisibleItems
        public static bool HasVisibleItems(g menuBuilder)
        {
            if (menuBuilder.A != false)
            {
                return true;
            }
        
            int groupId = menuBuilder.size(menuBuilder);
            for (int itemIndex = 0; itemIndex < groupId; itemIndex++)
            {
                ArrayList menuItems = menuBuilder.g;
                object menuItem = menuItems.get(menuItems, itemIndex);
                i checkCast = (i)menuItem;
                bool isVisibleItem = checkCast.isVisible(checkCast);
        
                if (isVisibleItem)
                {
                    return true;
                }
            }
        
            return false;
        }

        // Original: setGroupCheckable
        public static void setGroupCheckable(MenuBuilder menuBuilder, int groupId, bool isEnabled, bool isExclusive)
        {
          ArrayList menuItems = menuBuilder.menuItems;
          int groupCount = menuItems.Count;
        
          for (int itemIndex = 0; itemIndex < groupCount; itemIndex++)
          {
            var menuItem = menuItems[itemIndex];
            if (menuItem.GroupId == groupId)
            {
              menuItem.IsExclusive = isExclusive;
              menuItem.IsCheckable = isEnabled;
            }
          }
        }

        // Original: setGroupDividerEnabled
        public static void SetGroupDividerEnabled(ref MenuBuilder menuBuilder, bool groupId)
        {
            menuBuilder.z = groupId;
        }

        // Original: setGroupEnabled
        public static void SetGroupEnabled(g menuBuilder, int groupId, bool isEnabled)
        {
            ArrayList menuItems = menuBuilder.g;
            int groupCount = menuItems.Count;
        
            for (int itemIndex = 0; itemIndex < groupCount; itemIndex++)
            {
                menuItem = menuItems[itemIndex];
                if ((int)menuItem.getGroupId() == groupId)
                {
                    menuItem.setEnabled(isEnabled);
                }
            }
        }

    }
}
