// Utilities2.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities2
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct ComponentActivity { a* mContextAwareHelper; } ComponentActivity;
        */

        /*
typedef struct OnBackPressedDispatcher_LifecycleOnBackPressedCancellable { OnBackPressedDispatcher* d; g* a; b* b; a* c; void (*<init>)(void*); void (*cancel)(void*); } OnBackPressedDispatcher_LifecycleOnBackPressedCancellable;
        */

        /*
typedef struct a { void (*a)(void*, b*); void (*e)(void*, b*); } a;
        */

        /*
typedef struct g { void (*c)(void*, void*); } g;
        */

        /*
typedef struct b { void (*b)(void*); } b;
        */

        /*
typedef struct OnBackPressedDispatcher { void (*b)(void*, b*); } OnBackPressedDispatcher;
        */

        /*
typedef struct c { void (*setVisible)(void*, bool, bool); void (*invalidateDrawable)(void*, Drawable*); void (*scheduleDrawable)(void*, Drawable*, Runnable*, long); void (*unscheduleDrawable)(void*, Drawable*, Runnable*); } c;
        */

        /*
typedef struct a_c { void (*newDrawable)(void*); void (*newDrawable)(void*, Resources*); } a_c;
        */

        /*
typedef struct d { bool (*setVisible)(void*, bool, bool); void (*invalidateDrawable)(void*, Drawable*); void (*scheduleDrawable)(void*, Drawable*, Runnable*, long); void (*unscheduleDrawable)(void*, Drawable*, Runnable*); } d;
        */

        /*
typedef struct b_b { void (*scheduleDrawable)(void*, Drawable*, Runnable*, long); } b_b;
        */

        /*
typedef struct a_g { void (*c)(void*); } a_g;
        */

        // Original: addOnContextAvailableListener
        public static void AddOnContextAvailableListener(ComponentActivity activity, b listener)
        {
            a callback = activity.mContextAwareHelper;
            if (callback != null)
            {
                callback.a(callback, listener);
            }
        }

        // Original: removeOnContextAvailableListener
        public static void removeOnContextAvailableListener(ComponentActivity activity, b listener)
        {
            a callback = activity.mContextAwareHelper;
            if (callback != null)
            {
                callback.e(callback, listener);
            }
        }

        // Original: OnBackPressedDispatcher$LifecycleOnBackPressedCancellable
        public static void OnBackPressedDispatcher_LifecycleOnBackPressedCancellable(OnBackPressedDispatcher_LifecycleOnBackPressedCancellable drawableContainer, OnBackPressedDispatcher drawable, g drawableCallback, b delay)
        {
            drawableContainer.d = drawable;
            drawableContainer.<init> = drawable;
            drawableContainer.a = drawableCallback;
            drawableContainer.b = delay;
            drawableCallback.a(drawableCallback, drawableContainer);
        }

        // Original: cancel
        public static void Cancel(OnBackPressedDispatcher_LifecycleOnBackPressedCancellable drawableContainer)
        {
            g drawableCallback;
            b drawable;
            a cancelable;
        
            drawableCallback = *drawableContainer->a;
            (*drawableCallback->c)(drawableCallback, drawableContainer);
        
            drawable = *drawableContainer->b;
            (*drawable->e)(drawable, drawableContainer);
        
            cancelable = *drawableContainer->c;
            if (cancelable != null)
            {
                (*cancelable->cancel)(cancelable);
                *drawableContainer->c = null;
            }
        }

        // Original: a
        public static void OnBackPressedDispatcher_LifecycleOnBackPressedCancellable_a(OnBackPressedDispatcher_LifecycleOnBackPressedCancellable drawableContainer, k drawable, g_b drawableCallback) {
            a backPressCancellable;
        
            if (drawableCallback == g_b_ON_START) {
                drawable = drawableContainer.d;
                backPressCancellable = drawable.b(drawable, drawableContainer.b);
                drawableContainer.c = backPressCancellable;
            } else if (drawableCallback == g_b_ON_STOP) {
                backPressCancellable = drawableContainer.c;
                if (backPressCancellable != null) {
                    backPressCancellable.cancel();
                }
            } else if (drawableCallback == g_b_ON_DESTROY) {
                drawableContainer.cancel();
            }
        }

        // Original: newDrawable
        public static Drawable NewDrawable(a_c drawableContainer)
        {
            a drawableCallback;
            drawableCallback = new a(drawableContainer, (Resources)0x0);
            return drawableCallback;
        }

        // Original: newDrawable
        public static Drawable newDrawable(a_c drawableContainer, Resources drawable)
        {
            a drawableCallback;
        
            drawableCallback = new a(drawableContainer, drawable);
            return drawableCallback;
        }

        // Original: setVisible
        public static bool setVisible(a drawableContainer, bool drawable, bool drawableCallback)
        {
            bool isVisibleSet;
            a_g drawable;
        
            isVisibleSet = base.setVisible(drawableContainer, drawable, drawableCallback);
            drawable = *(a_g*)drawableContainer.v;
        
            if (drawable != null && (isVisibleSet || drawableCallback))
            {
                if (drawable != null)
                {
                    drawable.c(drawable);
                }
                else
                {
                    drawableContainer.jumpToCurrentState();
                }
            }
        
            return isVisibleSet;
        }

        // Original: invalidateDrawable
        public void InvalidateDrawable(Drawable drawable)
        {
            base.InvalidateDrawable(drawable);
        }

        // Original: scheduleDrawable
        public static void ScheduleDrawable(Drawable drawableContainer, Drawable drawable, Runnable drawableCallback, long delay)
        {
            ((Lc.a.l.a.d)drawableContainer).ScheduleDrawable(drawable, drawableCallback, delay);
        }

        // Original: unscheduleDrawable
        public static void UnscheduleDrawable(Drawable drawableContainer, Drawable drawable, Runnable drawableCallback)
        {
            ((IDrawable)drawableContainer).UnscheduleDrawable(drawable, drawableCallback);
        }

        // Original: scheduleDrawable
        public static void ScheduleDrawable(b_b drawableContainer, Drawable drawable, Runnable drawableCallback, long delay)
        {
            Drawable_Callback callback = drawableContainer.f;
            if (callback != null)
            {
                callback.scheduleDrawable(drawable, drawableCallback, delay);
            }
        }

    }
}
