// Utilities6.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities6
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct b { int (*isVisible)(b*); } b;
        */

        /*
typedef struct a { int (*hasVisibleItems)(a*); void (*setGroupCheckable)(a*, int, boolean, boolean); void (*setGroupEnabled)(a*, int, boolean); void (*setGroupVisible)(a*, int, boolean); } a;
        */

        /*
typedef struct g { void (*setGroupDividerEnabled)(g*, boolean); } g;
        */

        /*
typedef struct d { void (*b)(d*); } d;
        */

        /*
typedef struct s { void (*b)(s*); } s;
        */

        // Original: isVisible
        public static bool isVisible(object autoCompleteTextView)
        {
            var menuGroup = (b)autoCompleteTextView.GetType().GetField("d").GetValue(autoCompleteTextView);
            return menuGroup.isVisible();
        }

        // Original: hasVisibleItems
        public static bool HasVisibleItems(o autoCompleteTextView)
        {
            a menuGroup;
        
            menuGroup = *autoCompleteTextView.d;
            bool isStateful = (*menuGroup.hasVisibleItems)(menuGroup);
            return isStateful;
        }

        // Original: setGroupCheckable
        public static void SetGroupCheckable(o autoCompleteTextView, Drawable drawable, bool isVisible, bool shouldCheckSubItems)
        {
            a menuGroup = *autoCompleteTextView.d;
            (*menuGroup.setGroupCheckable)(menuGroup, drawable, isVisible, shouldCheckSubItems);
        }

        // Original: setGroupEnabled
        public static void SetGroupEnabled(o autoCompleteTextView, Drawable drawable, bool isVisible)
        {
            a menuGroup = *autoCompleteTextView.d;
            menuGroup.setGroupEnabled(menuGroup, drawable, isVisible);
        }

        // Original: setGroupVisible
        public static void SetGroupVisible(o autoCompleteTextView, Drawable drawable, bool isVisible)
        {
            a menuGroup = *autoCompleteTextView.d;
            menuGroup.setGroupVisible(menuGroup, drawable, isVisible);
        }

        // Original: setGroupDividerEnabled
        public static void SetGroupDividerEnabled(r autoCompleteTextView, bool drawable)
        {
            g menuGroup;
            menuGroup = *autoCompleteTextView.B;
            (*menuGroup.setGroupDividerEnabled)(menuGroup, drawable);
        }

        // Original: verifyDrawable
        public static bool VerifyDrawable(ActionBarContainer autoCompleteTextView, Drawable drawable)
        {
            bool isStateful;
        
            if ((drawable == autoCompleteTextView.j && !autoCompleteTextView.m) ||
                (drawable == autoCompleteTextView.k && autoCompleteTextView.n != false) ||
                (drawable == autoCompleteTextView.l && autoCompleteTextView.m != false))
            {
                isStateful = true;
            }
            else
            {
                isStateful = super.VerifyDrawable(autoCompleteTextView, drawable);
            }
        
            return isStateful;
        }

        // Original: drawableStateChanged
        public static void drawableStateChanged(ActionBarContainer autoCompleteTextView)
        {
            bool isStateful;
            int[] drawableState;
            Drawable drawable;
        
            base.drawableStateChanged(autoCompleteTextView);
        
            drawable = autoCompleteTextView.j;
            if (drawable != null && (isStateful = drawable.isStateful(), isStateful))
            {
                drawableState = autoCompleteTextView.getDrawableState();
                drawable.setState(drawableState);
            }
        
            drawable = autoCompleteTextView.k;
            if (drawable != null && (isStateful = drawable.isStateful(), isStateful))
            {
                drawableState = autoCompleteTextView.getDrawableState();
                drawable.setState(drawableState);
            }
        
            drawable = autoCompleteTextView.l;
            if (drawable != null && (isStateful = drawable.isStateful(), isStateful))
            {
                drawableState = autoCompleteTextView.getDrawableState();
                drawable.setState(drawableState);
            }
        }

        // Original: jumpDrawablesToCurrentState
        public static void JumpDrawablesToCurrentState(ActionBarContainer autoCompleteTextView)
        {
            Drawable drawable;
        
            base.JumpDrawablesToCurrentState(autoCompleteTextView);
        
            drawable = autoCompleteTextView.j;
            if (drawable != null)
            {
                drawable.JumpToCurrentState();
            }
        
            drawable = autoCompleteTextView.k;
            if (drawable != null)
            {
                drawable.JumpToCurrentState();
            }
        
            drawable = autoCompleteTextView.l;
            if (drawable != null)
            {
                drawable.JumpToCurrentState();
            }
        }

        // Original: setHideOnContentScrollEnabled
        public static void SetHideOnContentScrollEnabled(ActionBarOverlayLayout layout, bool drawable)
        {
            if (layout.HideOnContentScrollEnabled != drawable)
            {
                layout.HideOnContentScrollEnabled = drawable;
                if (!drawable)
                {
                    layout.OnActionBarVisibilityChanged(false);
                    layout.SetActionBarHideOffset(0);
                }
            }
        }

        // Original: drawableStateChanged
        public static void drawableStateChanged(c autoCompleteTextView)
        {
            d drawableRef;
            s listener;
        
            base.drawableStateChanged(autoCompleteTextView);
            drawableRef = *autoCompleteTextView->g;
            if (drawableRef != null)
            {
                (*drawableRef->b)(drawableRef);
            }
            listener = *autoCompleteTextView->h;
            if (listener != null)
            {
                (*listener->b)(listener);
            }
        }

        // Original: setBackgroundDrawable
        public static void SetBackgroundDrawable(AutoCompleteTextView autoCompleteTextView, Drawable drawable)
        {
            ((T)autoCompleteTextView).setBackgroundDrawable(drawable);
        
            d drawableRef = (d)autoCompleteTextView.g;
            if (drawableRef != null)
            {
                drawableRef.f(drawableRef, drawable);
            }
        }

    }
}
