// Utilities7.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities7
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct s { int x; int y; } s;
        */

        /*
typedef struct d { void (*b)(d*); void (*f)(d*, Drawable*); } d;
        */

        /*
typedef struct g { void (*f)(g*); } g;
        */

        /*
typedef struct ColorStateList { /* ... */ } ColorStateList;
        */

        /*
typedef enum PorterDuff_Mode { /* ... */ } PorterDuff_Mode;
        */

        // Original: getSupportCompoundDrawablesTintList
        public static ColorStateList GetSupportCompoundDrawablesTintList(AppCompatButton drawable)
        {
            s buttonState = *(s*)drawable.g;
            ColorStateList context = ((Func<s, ColorStateList>)buttonState.j)(buttonState);
            return context;
        }

        // Original: getSupportCompoundDrawablesTintMode
        public static class AppCompatButton
        {
            public static PorterDuff_Mode GetSupportCompoundDrawablesTintMode(AppCompatButton drawable)
            {
                s buttonState = *drawable.g;
                PorterDuff_Mode tintMode = (*buttonState.k)(buttonState);
                return tintMode;
            }
        }

        // Original: getAutoSizeTextAvailableSizes
        public static int[] GetAutoSizeTextAvailableSizes(AppCompatButton drawable)
        {
            if (d_a != false)
            {
                return drawable.getAutoSizeTextAvailableSizes();
            }
        
            s drawableStateListener = drawable.g;
            if (drawableStateListener != null)
            {
                return drawableStateListener.h();
            }
        
            return new int[0];
        }

        // Original: drawableStateChanged
        public static void drawableStateChanged(AppCompatButton drawable)
        {
            d drawableStateListener;
            s stateListener;
        
            base.drawableStateChanged(drawable);
            drawableStateListener = *drawable.f;
            if (drawableStateListener != null)
            {
                drawableStateListener.b();
            }
            stateListener = *drawable.g;
            if (stateListener != null)
            {
                stateListener.b();
            }
        }

        // Original: setBackgroundDrawable
        public static void SetBackgroundDrawable(AppCompatButton drawable, Drawable drawableId)
        {
            drawable.setBackgroundDrawable(drawableId);
            d drawableStateListener = drawable.f;
            if (drawableStateListener != null)
            {
                drawableStateListener.f(drawableStateListener, drawableId);
            }
        }

        // Original: setSupportCompoundDrawablesTintList
        public static void SetSupportCompoundDrawablesTintList(AppCompatButton drawable, ColorStateList drawableId)
        {
            var buttonState = *(AppCompatButton.ButtonState*)drawable.g;
            buttonState.v(buttonState, drawableId);
            buttonState = *(AppCompatButton.ButtonState*)drawable.g;
            buttonState.b(buttonState);
        }

        // Original: setSupportCompoundDrawablesTintMode
        public static void SetSupportCompoundDrawablesTintMode(AppCompatButton drawable, PorterDuff_Mode drawableId)
        {
            var buttonState = drawable.g;
            buttonState.w(buttonState, drawableId);
            buttonState.b(buttonState);
        }

        // Original: drawableStateChanged
        public static void drawableStateChanged(e drawable)
        {
            d drawableStateListener;
            s stateListener;
        
            base.drawableStateChanged(drawable);
            drawableStateListener = *drawable->g;
            if (drawableStateListener != null)
            {
                (*drawableStateListener->b)(drawableStateListener);
            }
            stateListener = *drawable->h;
            if (stateListener != null)
            {
                (*stateListener->b)(stateListener);
            }
        }

        // Original: setBackgroundDrawable
        public void setBackgroundDrawable(Drawable drawable)
        {
            base.setBackgroundDrawable(drawable);
            d drawableStateListener = (d)drawable.g;
            if (drawableStateListener != null)
            {
                drawableStateListener.f(drawableStateListener, drawable);
            }
        }

        // Original: setButtonDrawable
        public void SetButtonDrawable(Drawable drawable, DrawableId drawableId)
        {
            base.SetButtonDrawable(drawable, drawableId);
            var drawableStateListener = drawable.f;
            if (drawableStateListener != null)
            {
                drawableStateListener.f(drawableStateListener);
            }
        }

        // Original: setButtonDrawable
        public static void SetButtonDrawable(Drawable drawable, int drawableId)
        {
            Context context = drawable.GetContext();
            Drawable buttonDrawable = AppCompatResources.GetDrawable(context, drawableId);
            drawable.SetButtonDrawable(buttonDrawable);
        }

        // Original: drawableStateChanged
        public class AppCompatCheckedTextView : CheckedTextView
        {
            protected override void drawableStateChanged()
            {
                base.drawableStateChanged();
                s drawableStateListener = this.g;
                if (drawableStateListener != null)
                {
                    drawableStateListener.b(drawableStateListener);
                }
            }
        }

    }
}
