// Utilities1.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities1
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct ParcelableVolumeInfo { int f; int h; int i; int j; int g; } ParcelableVolumeInfo;
        */

        /*
typedef struct ParcelableVolumeInfo_a { void (*a)(ParcelableVolumeInfo_a*, Parcel*); void (*b)(ParcelableVolumeInfo_a*, int); } ParcelableVolumeInfo_a;
        */

        // Original: read
        public static IconCompat Read(VersionedParcel parcel)
        {
            return IconCompatParcelizer_Read(parcel);
        }

        // Original: IconCompatParcelizer
        public class IconCompatParcelizer
        {
            public IconCompatParcelizer()
            {
                // Constructor logic here
            }
        }

        // Original: write
        public static void Write(IconCompat icon, VersionedParcel parcel)
        {
            IconCompatParcelizer_write(icon, parcel);
        }

        // Original: a
        public static ParcelableVolumeInfo CreateFromParcel(Parcel parcel) {
            return new ParcelableVolumeInfo(parcel);
        }

        // Original: b
        public static ParcelableVolumeInfo[] b(ParcelableVolumeInfo_a activity, VersionedParcel parcel) {
            ParcelableVolumeInfo[] volumeInfoArray = new ParcelableVolumeInfo[parcel.size()];
            return volumeInfoArray;
        }

        // Original: createFromParcel
        public static ParcelableVolumeInfo CreateFromParcel(ParcelableVolumeInfo_a activity, Parcel parcel)
        {
            ParcelableVolumeInfo volumeInfo;
        
            volumeInfo = activity.a(activity, parcel);
            return volumeInfo;
        }

        // Original: newArray
        public static ParcelableVolumeInfo[] newArray(ParcelableVolumeInfo_a activity, VersionedParcel parcel)
        {
            ParcelableVolumeInfo[] volumeInfoArray;
            volumeInfoArray = activity.b(activity, parcel);
            return volumeInfoArray;
        }

        // Original: ParcelableVolumeInfo$a
        public static class ParcelableVolumeInfo_a
        {
            public ParcelableVolumeInfo_a()
            {
                this();
            }
        }

        // Original: ParcelableVolumeInfo
        public static class ParcelableVolumeInfo
        {
            private static ParcelableVolumeInfoCreator CREATOR;
        
            public ParcelableVolumeInfo()
            {
                ParcelableVolumeInfoCreator creator = new ParcelableVolumeInfoCreator();
                CREATOR = creator;
            }
        }

        // Original: ParcelableVolumeInfo
        public class ParcelableVolumeInfo
        {
            private int f;
            private int h;
            private int i;
            private int j;
            private int g;
        
            public ParcelableVolumeInfo(Parcel parcel)
            {
                f = parcel.ReadInt();
                h = parcel.ReadInt();
                i = parcel.ReadInt();
                j = parcel.ReadInt();
                g = parcel.ReadInt();
            }
        }

        // Original: writeToParcel
        public static void writeToParcel(ParcelableVolumeInfo activity, Parcel parcel, int volumeControlFlags)
        {
            parcel.writeInt(activity.f);
            parcel.writeInt(activity.h);
            parcel.writeInt(activity.i);
            parcel.writeInt(activity.j);
            parcel.writeInt(activity.g);
        }

        // Original: peekAvailableContext
        public static class ComponentActivity
        {
            public static Context PeekAvailableContext(ComponentActivity activity)
            {
                a contextHelper = *activity.mContextAwareHelper;
                Context availableContext = (*contextHelper.d)(contextHelper);
                return availableContext;
            }
        }

    }
}
