// utilities_7.c
// Auto-generated by Refactory Pipeline

#include "utilities_7.h"


// OnBackPressedCallback
void androidx::activity::OnBackPressedCallback::OnBackPressedCallback(OnBackPressedCallback *dispatcher, boolean callback) {
    CopyOnWriteArrayList *callbackList;

    (*dispatcher-><init>)(dispatcher);
    callbackList = new CopyOnWriteArrayList();
    *dispatcher->cancellablesList = callbackList;
    *dispatcher->mEnabled = callback;
}


// addCancellable
void androidx::activity::OnBackPressedCallback::addCancellable(OnBackPressedCallback *dispatcher, Cancellable *callback) {
    CopyOnWriteArrayList *lifecycle = *dispatcher->cancellablesList;
    lifecycle->add(callback);
}



// remove
void androidx::activity::OnBackPressedCallback::remove(OnBackPressedCallback *dispatcher) {
  CopyOnWriteArrayList *lifecycle = *dispatcher->cancellablesList;
  Iterator *callbackList = (*lifecycle->iterator)(lifecycle);

  while ((*callbackList->hasNext)(callbackList)) {
    Object *callback = (*callbackList->next)(callbackList);
    checkCast(callback, Cancellable);
    (*callback->cancel)(callback);
  }
}


// removeCancellable
void androidx::activity::OnBackPressedCallback::removeCancellable(OnBackPressedCallback *dispatcher, Cancellable *callback) {
    CopyOnWriteArrayList *lifecycle = *dispatcher->cancellablesList;
    (*lifecycle->remove)(lifecycle, callback);
}



// OnBackPressedDispatcher$LifecycleOnBackPressedCancellable
void androidx::activity::OnBackPressedDispatcher$LifecycleOnBackPressedCancellable::OnBackPressedDispatcher_LifecycleOnBackPressedCancellable(OnBackPressedDispatcher_LifecycleOnBackPressedCancellable *dispatcher, OnBackPressedDispatcher *callback, Lifecycle *onBackPressedCallback, OnBackPressedCallback *onBackPressedCallback) {
  *dispatcher->dispatcher$0 = callback;
  (*dispatcher-><init>)(dispatcher);
  *dispatcher->lifecycle = onBackPressedCallback;
  *dispatcher->onBackPressedCallback = onBackPressedCallback;
  (*onBackPressedCallback->addObserver)(onBackPressedCallback, dispatcher);
}


// cancel
void androidx::activity::OnBackPressedDispatcher$LifecycleOnBackPressedCancellable::cancel(OnBackPressedDispatcher_LifecycleOnBackPressedCancellable *dispatcher) {
    Lifecycle *lifecycle = *dispatcher->lifecycle;
    OnBackPressedCallback *callbackList = *dispatcher->onBackPressedCallback;
    Cancellable *callback = *dispatcher->currentCancellable;

    (*lifecycle->removeObserver)(lifecycle, dispatcher);
    (*callbackList->removeCancellable)(callbackList, dispatcher);

    if (callback != nullptr) {
        (*callback->cancel)(callback);
        *dispatcher->currentCancellable = nullptr;
    }
}


// onStateChanged
void androidx::activity::OnBackPressedDispatcher$LifecycleOnBackPressedCancellable::onStateChanged(OnBackPressedDispatcher_LifecycleOnBackPressedCancellable *dispatcher, LifecycleOwner *callback, Lifecycle_Event *onBackPressedCallback) {
    Cancellable *cancellable;
    OnBackPressedDispatcher *callbackList;

    if (onBackPressedCallback == *Lifecycle_Event_ON_START) {
        callbackList = *dispatcher->dispatcher$0;
        cancellable = (*callbackList->addCancellableCallback)(callbackList, *dispatcher->onBackPressedCallback);
        *dispatcher->currentCancellable = cancellable;
    } else if (onBackPressedCallback == *Lifecycle_Event_ON_STOP) {
        cancellable = *dispatcher->currentCancellable;
        if (cancellable != (Cancellable *)0x0) {
            (*cancellable->cancel)(cancellable);
        }
    } else if (onBackPressedCallback == *Lifecycle_Event_ON_DESTROY) {
        (*dispatcher->cancel)(dispatcher);
    }
}


// OnBackPressedDispatcher$OnBackPressedCancellable
void androidx::activity::OnBackPressedDispatcher$OnBackPressedCancellable::OnBackPressedDispatcher_OnBackPressedCancellable(OnBackPressedDispatcher_OnBackPressedCancellable *dispatcher, OnBackPressedDispatcher *callback, OnBackPressedCallback *onBackPressedCallback) {
    *dispatcher->dispatcher$0 = callback;
    (*dispatcher-><init>)(dispatcher);
    *dispatcher->onBackPressedCallback = onBackPressedCallback;
}


// cancel
void androidx::activity::OnBackPressedDispatcher$OnBackPressedCancellable::cancel(OnBackPressedDispatcher_OnBackPressedCancellable *dispatcher) {
  ArrayDeque *callbackList = *(*dispatcher->dispatcher$0)->backPressCallbacks;
  (*callbackList->remove)(callbackList, *dispatcher->onBackPressedCallback);
  OnBackPressedCallback *callback = *dispatcher->onBackPressedCallback;
  (*callback->removeCancellable)(callback, dispatcher);
}


// addCancellableCallback
Cancellable* androidx::activity::OnBackPressedDispatcher::addCancellable(OnBackPressedDispatcher *dispatcher, OnBackPressedCallback *callback) {
    ArrayDeque *lifecycle = *dispatcher->backPressCallbacks;
    (*lifecycle->add)(lifecycle, callback);

    Cancellable *callbackList = new Cancellable(dispatcher, callback);
    (*callback->addCancellable)(callback, callbackList);

    return callbackList;
}


// hasEnabledCallbacks
boolean androidx::activity::OnBackPressedDispatcher::hasEnabledCallbacks(OnBackPressedDispatcher *dispatcher) {
  Iterator *callbackList;
  Object *callback;
  ArrayDeque *lifecycle = *dispatcher->backPressCallbacks;

  callbackList = (*lifecycle->descendingIterator)(lifecycle);

  while (true) {
    if (!(*callbackList->hasNext)(callbackList)) {
      return false;
    }

    callback = (*callbackList->next)(callbackList);
    checkCast(callback, OnBackPressedCallback);

    if ((*callback->isEnabled)(callback)) {
      break;
    }
  }

  return true;
}

