// utilities_3.c
// Auto-generated by Refactory Pipeline

#include "utilities_3.h"


// ResultReceiver
void android::support::v4::os::ResultReceiver::ResultReceiver(ResultReceiver *instance, Handler *requestCode) {
    instance-><init>(instance);
    instance->isHandlerSet = true;
    instance->handler = requestCode;
}


// ResultReceiver
void android::support::v4::os::ResultReceiver::ResultReceiver(ResultReceiver *instance, Parcel *requestCode) {
    (*instance-><init>)(instance);
    *instance->isHandlerSet = false;
    *instance->handler = (Handler *)0x0;
    IBinder *binder = (*requestCode->readStrongBinder)(requestCode);
    IResultReceiver *intent = (*IResultReceiver_Stub_asInterface)(binder);
    *instance->receiver = intent;
}


// send
void android::support::v4::os::ResultReceiver::send(ResultReceiver *instance, int requestCode, Bundle *activityResultContract) {
  Handler *myResultReceiver;
  IResultReceiver *handler;
  Runnable *runnable;

  if (*instance->isHandlerSet != false) {
    myResultReceiver = *instance->handler;
    if (myResultReceiver == (Handler *)0x0) {
      (*instance->onReceiveResult)(instance, requestCode, activityResultContract);
    } else {
      runnable = new Runnable(instance, requestCode, activityResultContract);
      (*myResultReceiver->post)(myResultReceiver, runnable);
    }
  } else {
    handler = *instance->receiver;
    if (handler != (IResultReceiver *)0x0) {
      (*handler->send)(handler, requestCode, activityResultContract);
    }
  }
}


// writeToParcel
void android::support::v4::os::ResultReceiver::writeToParcel(ResultReceiver *instance, Parcel *requestCode, int activityResultContract) {
    IBinder *binder;
    ResultReceiver_MyResultReceiver *myResultReceiver;
    IResultReceiver *handler;

    monitorEnter(instance);
    if (*instance->receiver == (IResultReceiver *)0x0) {
        myResultReceiver = new ResultReceiver$MyResultReceiver(instance);
        *instance->receiver = myResultReceiver;
    }
    handler = *instance->receiver;
    binder = (*handler->asBinder)(handler);
    (*requestCode->writeStrongBinder)(requestCode, binder);
    monitorExit(instance);
}


// ComponentActivity$1
void androidx::activity::ComponentActivity$1::ComponentActivity_1(ComponentActivity_1 *instance, ComponentActivity *requestCode) {
  *instance->instance$0 = requestCode;
  (*instance-><init>)(instance);
}


// run
void androidx::activity::ComponentActivity$1::run(ComponentActivity_1 *instance)
{
  (*ComponentActivity_access_001)(instance->instance$0);
}



// ComponentActivity$2$1
void androidx::activity::ComponentActivity$2$1::ComponentActivity_2_1(ComponentActivity_2_1 *instance, ComponentActivity_2 *requestCode, int activityResultContract, ActivityResultContract_SynchronousResult *input) {
  instance->instance$1 = requestCode;
  instance->requestCode = activityResultContract;
  instance->synchronousResult = input;
  (*instance-><init>)(instance);
}


// run
void androidx::activity::ComponentActivity$2$1::run(ComponentActivity_2_1 *instance) {
    ComponentActivity_2 *context = *instance->instance$1;
    int requestCode = *instance->requestCode;
    ActivityResultContract_SynchronousResult *myResultReceiver = *instance->synchronousResult;

    Object *resultValue = (*myResultReceiver->getValue)(myResultReceiver);
    (*context->dispatchResult)(context, requestCode, resultValue);
}



// ComponentActivity$2$2
void androidx::activity::ComponentActivity$2$2::ComponentActivity_2_2
(
    ComponentActivity_2_2 *instance,
    ComponentActivity_2 *requestCode,
    int activityResultContract,
    IntentSender_SendIntentException *input
)
{
    instance->instance$1 = requestCode;
    instance->requestCode = activityResultContract;
    instance->val$e = input;
    (*instance-><init>)(instance);
}



// run
void androidx::activity::ComponentActivity$2$2::run(ComponentActivity_2_2 *instance)
{
    ComponentActivity_2 *context = *instance->instance$1;
    int requestCode = *instance->requestCode;

    Intent intent = new Intent();
    intent.setAction("androidx.activity.result.contract.action.INTENT_SENDER_REQUEST");
    intent.putExtra("androidx.activity.result.contract.extra.SEND_INTENT_EXCEPTION", *instance->val$e);

    context.dispatchResult(context, requestCode, 0, intent);
}


// ComponentActivity$2
void androidx::activity::ComponentActivity$2::ComponentActivity_2(ComponentActivity_2 *instance, ComponentActivity *requestCode) {
    *instance->instance$0 = requestCode;
    (*instance->ActivityResultRegistry)(instance);
}


