// utilities_6.c
// Auto-generated by Refactory Pipeline

#include "utilities_6.h"


// onActivityResult
void androidx::activity::ComponentActivity::onActivityResult
               (ComponentActivity *self,int activity,int layoutParams,Intent *grantResults)
{
  boolean isTracingEnabled;
  ActivityResultRegistry *local_0;

  local_0 = *self->activityResultRegistry;
  isTracingEnabled = (*local_0->dispatchResult)(local_0,activity,layoutParams,grantResults);
  if (!isTracingEnabled) {
    (*super->onActivityResult)(self,activity,layoutParams,grantResults);
  }
  return;
}


// onBackPressed
void androidx::activity::ComponentActivity::onBackPressed(ComponentActivity *self) {
  OnBackPressedDispatcher *dispatcher = *self->backPressedDispatcher;
  dispatcher->onBackPressed();
}


// onCreate
void androidx::activity::ComponentActivity::onCreate(ComponentActivity *self, Bundle *activity)
{
  SavedStateRegistryController *local_0;
  ContextAwareHelper *ref;

  local_0 = *self->savedStateRegistryController;
  (*local_0->performRestore)(local_0, activity);

  ref = *self->contextAwareHelper;
  (*ref->dispatchOnContextAvailable)(ref, self);

  (*super->onCreate)(self, activity);

  (*ReportFragment_injectIfNeededIn)(self);

  int contentLayoutId = *self->contentLayoutId;
  if (contentLayoutId != 0)
  {
    (*self->setContentView)(self, contentLayoutId);
  }
}


// onRequestPermissionsResult
void androidx::activity::ComponentActivity::onRequestPermissionsResult(ComponentActivity *self, int activity, String **layoutParams, int *grantResults) {
    ActivityResultRegistry *local_0 = *self->activityResultRegistry;
    Intent *inputMethodManager = new Intent();
    inputMethodManager = (*inputMethodManager->putExtra)(inputMethodManager, (String *)"androidx.activity.result.contract.extra.PERMISSIONS", layoutParams);
    inputMethodManager = (*inputMethodManager->putExtra)(inputMethodManager, (String *)"androidx.activity.result.contract.extra.PERMISSION_GRANT_RESULTS", grantResults);

    boolean isTracingEnabled = (*local_0->dispatchResult)(local_0, activity, -1, inputMethodManager);

    if (!isTracingEnabled && (0x16 < *Build_VERSION_SDK_INT)) {
        (*super->onRequestPermissionsResult)(self, activity, layoutParams, grantResults);
    }
}


// onSaveInstanceState
void androidx::activity::ComponentActivity::onSaveInstanceState(ComponentActivity *self, Bundle *activity) {
    Lifecycle *lifecycle = (*self->getLifecycle)(self);
    if (instanceof(lifecycle, LifecycleRegistry)) {
        checkCast(lifecycle, LifecycleRegistry);
        (*lifecycle->setCurrentState)(lifecycle, Lifecycle_State_CREATED);
    }
    (*super->onSaveInstanceState)(self, activity);
    SavedStateRegistryController *controller = *self->savedStateRegistryController;
    (*controller->performSave)(controller, activity);
}



// removeOnContextAvailableListener
void androidx::activity::ComponentActivity::removeOnContextAvailableListener(ComponentActivity *self, OnContextAvailableListener *activity) {
    ContextAwareHelper *local_0 = *self->contextAwareHelper;
    (*local_0->removeOnContextAvailableListener)(local_0, activity);
}


// setContentView
void androidx::activity::ComponentActivity::setContentView(ComponentActivity *self, View *activity) {
  self->initViewTreeOwners(self);
  super->setContentView(self, activity);
}


// setContentView
void androidx::activity::ComponentActivity::setContentView(ComponentActivity *self, View *activity, ViewGroup_LayoutParams *layoutParams) {
  (*self->initViewTreeOwners)(self);
  (*super->setContentView)(self, activity, layoutParams);
}


// setContentView
void androidx::activity::ComponentActivity::setContentView(ComponentActivity *self, int activity) {
  self->initViewTreeOwners(self);
  super->setContentView(self, activity);
}


// ImmLeaksCleaner
void androidx::activity::ImmLeaksCleaner::ImmLeaksCleaner(ImmLeaksCleaner *self, Activity *activity) {
  (*self-><init>)(self);
  *self->mActivity = activity;
}

