// utilities_4.c
// Auto-generated by Refactory Pipeline

#include "utilities_4.h"


// ComponentActivity$3
void androidx::activity::ComponentActivity$3::ComponentActivity_3(ComponentActivity_3 *componentActivityInstance, ComponentActivity *activityResultContract) {
  componentActivityInstance->componentActivityInstance$0 = activityResultContract;
  (*componentActivityInstance-><init>)(componentActivityInstance);
}


// onStateChanged
void androidx::activity::ComponentActivity$3::onStateChanged(ComponentActivity_3 *componentActivityInstance, LifecycleOwner *activityResultContract, Lifecycle_Event *activityResultCallback) {
    Window *savedStateRegistry;
    View *activityResultRegistry;
    ComponentActivity *componentActivity;

    if (activityResultCallback == *Lifecycle_Event_ON_STOP) {
        componentActivity = *componentActivityInstance->componentActivityInstance$0;
        savedStateRegistry = (*componentActivity->getWindow)(componentActivity);

        if (savedStateRegistry != nullptr) {
            activityResultRegistry = (*savedStateRegistry->peekDecorView)(savedStateRegistry);
        } else {
            activityResultRegistry = nullptr;
        }

        if (activityResultRegistry != nullptr) {
            (*activityResultRegistry->cancelPendingInputEvents)(activityResultRegistry);
        }
    }
}



// ComponentActivity$4
void androidx::activity::ComponentActivity$4::ComponentActivity_4(ComponentActivity_4 *componentActivityInstance, ComponentActivity *activityResultContract) {
  componentActivityInstance->componentActivityInstance$0 = activityResultContract;
  (*componentActivityInstance-><init>)(componentActivityInstance);
}


// onStateChanged
void androidx::activity::ComponentActivity$4::onStateChanged
               (ComponentActivity_4 *componentActivityInstance, LifecycleOwner *activityResultContract, Lifecycle_Event *activityResultCallback)
{
  ViewModelStore *savedStateRegistry;
  ContextAwareHelper *activityResultRegistry;
  ComponentActivity *pCVar2;

  if (activityResultCallback == *Lifecycle_Event_ON_DESTROY) {
    activityResultRegistry = *(*componentActivityInstance->componentActivityInstance$0)->contextAwareHelper;
    (*activityResultRegistry->clearAvailableContext)(activityResultRegistry);

    pCVar2 = *componentActivityInstance->componentActivityInstance$0;
    if (!(*pCVar2->isChangingConfigurations)(pCVar2)) {
      savedStateRegistry = (*pCVar2->getViewModelStore)(pCVar2);
      (*savedStateRegistry->clear)(savedStateRegistry);
    }
  }

  return;
}


// ComponentActivity$5
void androidx::activity::ComponentActivity$5::ComponentActivity_5(ComponentActivity_5 *componentActivityInstance, ComponentActivity *activityResultContract) {
    *componentActivityInstance->componentActivityInstance$0 = activityResultContract;
    (*componentActivityInstance-><init>)(componentActivityInstance);
}


// onStateChanged
void androidx::activity::ComponentActivity$5::onStateChanged
               (ComponentActivity_5 *componentActivityInstance,LifecycleOwner *activityResultContract,Lifecycle_Event *activityResultCallback)
{
  Lifecycle *savedStateRegistry;
  ComponentActivity *context;

  context = *componentActivityInstance->componentActivityInstance$0;
  (*context->ensureViewModelStore)(context);
  context = *componentActivityInstance->componentActivityInstance$0;
  savedStateRegistry = (*context->getLifecycle)(context);
  (*savedStateRegistry->removeObserver)(savedStateRegistry,componentActivityInstance);
  return;
}


// saveState
Bundle * androidx::activity::ComponentActivity$6::saveState(ComponentActivity_6 *componentActivityInstance) {
    ActivityResultRegistry *savedStateRegistry;
    Bundle *helper;

    helper = new Bundle();
    savedStateRegistry = (*ComponentActivity_access_100)(*componentActivityInstance->componentActivityInstance$0);
    (*savedStateRegistry->onSaveInstanceState)(savedStateRegistry, helper);
    return helper;
}


// ComponentActivity$6
void androidx::activity::ComponentActivity$6::ComponentActivity_6(ComponentActivity_6 *componentActivityInstance, ComponentActivity *activityResultContract) {
    *componentActivityInstance->componentActivityInstance$0 = activityResultContract;
    (*componentActivityInstance-><init>)(componentActivityInstance);
}


// ComponentActivity$7
void androidx::activity::ComponentActivity$7::ComponentActivity_7(ComponentActivity_7 *componentActivityInstance, ComponentActivity *activityResultContract) {
    *componentActivityInstance->componentActivityInstance$0 = activityResultContract;
    (*componentActivityInstance-><init>)(componentActivityInstance);
    return;
}


// peekAvailableContext
Context* androidx::activity::ComponentActivity::peekAvailableContext(ComponentActivity* componentActivityInstance) {
    Context* context;
    ContextAwareHelper* helper;

    helper = *componentActivityInstance->contextAwareHelper;
    context = (*helper->peekAvailableContext)(helper);

    return context;
}


// registerForActivityResult
ActivityResultLauncher *androidx::activity::ComponentActivity::registerForActivityResult(ComponentActivity *componentActivityInstance, ActivityResultContract *activityResultContract, ActivityResultCallback *activityResultCallback) {
    return (*componentActivityInstance->registerForActivityResult)(componentActivityInstance, activityResultContract, componentActivityInstance->activityResultRegistry, activityResultCallback);
}

