// utilities_2.c
// Auto-generated by Refactory Pipeline

#include "utilities_2.h"


// setDefaultImpl
bool android::support::v4::os::IResultReceiver$Stub::setDefaultImpl(IResultReceiver* receiver) {
  if (*IResultReceiver_Stub_Proxy_sDefaultImpl != nullptr) {
    throw new IllegalStateException("setDefaultImpl() called twice");
  }

  if (receiver != nullptr) {
    *IResultReceiver_Stub_Proxy_sDefaultImpl = receiver;
    return true;
  }

  return false;
}


// createFromParcel
ResultReceiver* android::support::v4::os::ResultReceiver$1::createFromParcel(ResultReceiver_1* receiver, Parcel* parcel) {
    ResultReceiver* creatorInstance = new ResultReceiver(receiver);
    return creatorInstance;
}


// createFromParcel
Object* android::support::v4::os::ResultReceiver$1::createFromParcel(ResultReceiver_1* receiver, Parcel* parcel) {
    ResultReceiver* resultReceiver = (*receiver->createFromParcel)(receiver, parcel);
    return resultReceiver;
}


// newArray
Object** android::support::v4::os::ResultReceiver$1::newArray(ResultReceiver_1* receiver, int size) {
    Object** resultReceivers = (*receiver->newArray)(receiver, size);
    return resultReceivers;
}


// ResultReceiver$MyResultReceiver
void android::support::v4::os::ResultReceiver$MyResultReceiver::ResultReceiver_MyResultReceiver(ResultReceiver_MyResultReceiver *receiver, ResultReceiver *resultReceiver) {
    receiver->receiver$0 = resultReceiver;
    (*receiver->IResultReceiver$Stub)(receiver);
}



// send
void android::support::v4::os::ResultReceiver$MyResultReceiver::send(ResultReceiver_MyResultReceiver *receiver, int receiver, Bundle *resultCode) {
    Handler *exception;
    ResultReceiver *ref_00;
    Runnable *ref_01;

    if (*(*receiver->receiver$0)->mHandler == (Handler *)0x0) {
        ref_00 = *receiver->receiver$0;
        (*ref_00->onReceiveResult)(ref_00, receiver, resultCode);
    } else {
        exception = *(*receiver->receiver$0)->mHandler;
        ref_01 = new Runnable(*receiver->receiver$0, receiver, resultCode);
        (*exception->post)(exception, ref_01);
    }
}


// ResultReceiver$MyRunnable
void android::support::v4::os::ResultReceiver$MyRunnable::ResultReceiver_MyRunnable(ResultReceiver_MyRunnable *receiver, ResultReceiver *receiver, Parcel* resultCode, Bundle *resultData) {
    receiver->receiver$0 = receiver;
    receiver-><init>(receiver);
    receiver->resultCode = resultCode;
    receiver->resultData = resultData;
}


// run
void android::support::v4::os::ResultReceiver$MyRunnable::run(ResultReceiver_MyRunnable *receiver) {
    ResultReceiver *creatorInstance = *receiver->receiver$0;
    (*creatorInstance->onReceiveResult)(creatorInstance, receiver->resultCode, receiver->resultData);
}



// ResultReceiver
void android::support::v4::os::ResultReceiver::ResultReceiver(void) {
    ResultReceiver_1* creatorInstance = new ResultReceiver$1();
    *ResultReceiver_CREATOR = creatorInstance;
}

