// utilities_1.c
// Auto-generated by Refactory Pipeline

#include "utilities_1.h"


// INotificationSideChannel$Stub$Proxy
void android::support::v4::app::INotificationSideChannel$Stub$Proxy::INotificationSideChannel_Stub_Proxy(INotificationSideChannel_Stub_Proxy *proxyInstance, IBinder *resultCode) {
  (*proxyInstance-><init>)(proxyInstance);
  *proxyInstance->remoteBinder = resultCode;
}


// asInterface
INotificationSideChannel *android::support::v4::app::INotificationSideChannel$Stub::asInterface(IBinder *parcel) {
    if (parcel == nullptr) {
        return nullptr;
    }

    IInterface *icon = parcel->queryLocalInterface("android.support.v4.app.INotificationSideChannel");

    if (icon != nullptr && icon instanceof INotificationSideChannel) {
        checkCast(icon, INotificationSideChannel);
        return icon;
    }

    return new INotificationSideChannel$Stub$Proxy(parcel);
}


// setDefaultImpl
bool android::support::v4::app::INotificationSideChannel$Stub::setDefaultImpl(INotificationSideChannel *parcel) {
    if (*INotificationSideChannel_Stub_Proxy_sDefaultImpl != nullptr) {
        IllegalStateException *illegalStateException = new IllegalStateException("setDefaultImpl() called twice");
        throwException(illegalStateException);
        return false;
    }
    if (parcel != nullptr) {
        *INotificationSideChannel_Stub_Proxy_sDefaultImpl = parcel;
        return true;
    }
    return false;
}


// read
RemoteActionCompat *
android::support::v4::app::RemoteActionCompatParcelizer::read(VersionedParcel *parcel)
{
  RemoteActionCompat *remoteAction;

  remoteAction = (*RemoteActionCompatParcelizer_read)(parcel);
  return remoteAction;
}


// read
IconCompat *android::support::v4::graphics::drawable::IconCompatParcelizer::read(VersionedParcel *parcel) {
  IconCompat *icon;
  icon = (*IconCompatParcelizer_read)(parcel);
  return icon;
}


// IResultReceiver$Stub$Proxy
void android::support::v4::os::IResultReceiver$Stub$Proxy::IResultReceiver_Stub_Proxy(IResultReceiver_Stub_Proxy* proxyInstance, IBinder* resultCode) {
    (*proxyInstance-><init>)(proxyInstance);
    *proxyInstance->remoteBinder = resultCode;
}


// send
void android::support::v4::os::IResultReceiver$Stub$Proxy::send(IResultReceiver_Stub_Proxy *proxyInstance, IBinder* resultCode, Bundle *data) {
    Parcel *parcel = (*Parcel_obtain)();
    parcel->writeInterfaceToken("android.support.v4.os.IResultReceiver");
    parcel->writeInt(resultCode);

    if (data == nullptr) {
        parcel->writeInt(0);
    } else {
        parcel->writeInt(1);
        data->writeToParcel(parcel, 0);
    }

    IBinder *binder = proxyInstance->remoteBinder;
    bool result = binder->transact(1, parcel, nullptr, 1);

    if (!result) {
        IResultReceiver *defaultImpl = (*IResultReceiver_Stub_getDefaultImpl)();
        if (defaultImpl != nullptr) {
            defaultImpl->send(resultCode, data);
        }
    }

    parcel->recycle();
}

