// Utilities1.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities1
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct AVFormatterData { String* value; int* flags; ArrayList* additionalData; } AVFormatterData;
        */

        /*
typedef struct AVDTCData224 { ArrayList* DTCData; String* numberOfDTCReported; } AVDTCData224;
        */

        // Original: dataFromAV
        public static AVFormatterData dataFromAV(AVBooleanFormatter self, byte[] inputBuffer)
        {
            AVFormatterData result = new AVFormatterData();
            long totalValue = 0;
        
            for (int byteIndex = 0; byteIndex < 4; byteIndex++)
            {
                long currentByteValue = ((long)inputBuffer[byteIndex] & 0xffU);
                totalValue += currentByteValue << (8 * byteIndex);
            }
        
            if (totalValue == 0)
            {
                result.flags = 1;
            }
            else
            {
                result.flags = 2;
            }
        
            result.value = "Refer to flags.";
            return result;
        }

        // Original: AVDTCData224
        public class AVDTCData224
        {
            private List<string> DTCData;
        
            public AVDTCData224()
            {
                this.DTCData = new List<string>();
            }
        }

        // Original: AVDTCData225
        public class AVDTCData225
        {
            public List<string> DTCData { get; set; }
        
            public AVDTCData225()
            {
                DTCData = new List<string>();
            }
        }

        // Original: setDTCData
        public static void setDTCData(AVDTCData225 self, ArrayList inputBuffer)
        {
        	AVFormatterData local_0;
        	ArrayList dtcList;
        
        	for (local_0 = 0; local_0 < 6; local_0++)
        	{
        		dtcList = self.DTCData;
        		object pOVar1 = inputBuffer.get(local_0);
        		dtcList.add(pOVar1);
        	}
        }

        // Original: dataFromAV
        public static AVFormatterData dataFromAV(AVDTCFormatter224 self, byte[] inputBuffer)
        {
            AVFormatterData formatterData = new AVFormatterData();
            ArrayList dtcList = new ArrayList();
            string defaultString = "0";
        
            if (inputBuffer != null && inputBuffer.Length > 0)
            {
                int numberOfDTCs = inputBuffer[2];
                if (numberOfDTCs > 4)
                {
                    numberOfDTCs = 5;
                }
        
                string currentPrefix = "P";
        
                for (int i = 0; i < numberOfDTCs; i++)
                {
                    int index = i * 2 + 3;
                    string currentType = currentPrefix;
        
                    byte b1 = inputBuffer[index];
                    byte b2 = inputBuffer[index];
                    byte b3 = inputBuffer[index + 1];
                    byte b4 = inputBuffer[index + 1];
        
                    if ((b1 & 0xC0) != 0)
                    {
                        switch (b1 & 0xC0)
                        {
                            case 0x40:
                                currentType = "C";
                                break;
                            case 0x80:
                                currentType = "B";
                                break;
                            case 0xC0:
                                currentType = "U";
                                break;
                        }
                    }
        
                    formattedDataArray[0] = currentType;
                    formattedDataArray[1] = (int)((b1 & 0x30) >> 4);
                    formattedDataArray[2] = (int)(b2 & 0xF);
                    formattedDataArray[3] = (int)((b3 & 0xF0) >> 4);
                    formattedDataArray[4] = (int)(b4 & 0xF);
        
                    string dtcString = String.Format("{0}{1}{2}{3}{4}", formattedDataArray);
                    dtcList.Add(dtcString);
        
                    currentPrefix = currentType;
                }
            }
        
            formatterData.value = defaultString;
            AVDTCData224 avDTCData = new AVDTCData224();
            avDTCData.DTCData = dtcList;
            avDTCData.numberOfDTCReported = pSVar5;
            formatterData.additionalData = avDTCData;
        
            return formatterData;
        }

    }
}
