// Utilities1.cs
// Auto-generated by Refactory Pipeline

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;

namespace RefactoredApp
{
    public static class Utilities1
    {
        // Discovered Structs (Original C definitions)
        /*
typedef struct a { int x; int y; } a;
        */

        /*
typedef struct Uri { char *url; } Uri;
        */

        /*
typedef struct Bundle { void *data; } Bundle;
        */

        /*
typedef struct List { void **elements; int size; } List;
        */

        // Original: a
        public static Iterator a()
        {
            List<AndroidExceptionPreHandler> list = new List<AndroidExceptionPreHandler>();
            AndroidExceptionPreHandler handler = new AndroidExceptionPreHandler();
            list.Add(handler);
            return list.GetEnumerator();
        }

        // Original: b
        public static Iterator b()
        {
            List<AndroidDispatcherFactory> list = new List<AndroidDispatcherFactory>();
            AndroidDispatcherFactory factory = new AndroidDispatcherFactory();
            list.Add(factory);
            return list.GetEnumerator();
        }

        // Original: asInterface
        public static a asInterface(IBinder binder)
        {
            try
            {
                throw new RuntimeException("Stub!");
            }
            catch (RuntimeException ex)
            {
                return null;
            }
        }

        // Original: asBinder
        public static IBinder asBinder(a_a service)
        {
            RuntimeException exception = new RuntimeException("Stub!");
            throw exception;
        }

        // Original: onTransact
        public static bool onTransact(int code, Parcel dataInput, Parcel replyOutput)
        {
            try
            {
                throw new RuntimeException("Stub!");
            }
            catch (RuntimeException ex)
            {
                Console.WriteLine(ex.Message);
                return false;
            }
        }

        // Original: a$a
        public class PackageInstallObserver : Binder, IPackageInstallObserver
        {
            public PackageInstallObserver()
            {
                throw new RuntimeException("Stub!");
            }
        }

        // Original: onTransact
        public static bool onTransact(a_a service, int requestId, Parcel dataInput, Parcel replyOutput, List flags)
        {
            string interfaceDescriptor = "android.support.customtabs.ICustomTabsCallback";
        
            switch (requestId)
            {
                case 2:
                    dataInput.enforceInterface(interfaceDescriptor);
                    int result1 = dataInput.readInt();
                    int methodId1 = dataInput.readInt();
                    Bundle parcelableBundle1 = null;
        
                    if (methodId1 != 0)
                    {
                        parcelableBundle1 = (Bundle)Bundle_CREATOR.createFromParcel(dataInput);
                    }
        
                    service.r5(result1, parcelableBundle1);
                    replyOutput.writeNoException();
                    return true;
        
                case 3:
                    dataInput.enforceInterface(interfaceDescriptor);
                    string interfaceName = dataInput.readString();
                    int result2 = dataInput.readInt();
                    Bundle parcelableBundle2 = null;
        
                    if (result2 != 0)
                    {
                        parcelableBundle2 = (Bundle)Bundle_CREATOR.createFromParcel(dataInput);
                    }
        
                    service.N4(interfaceName, parcelableBundle2);
                    replyOutput.writeNoException();
                    return true;
        
                case 4:
                    dataInput.enforceInterface(interfaceDescriptor);
                    int result3 = dataInput.readInt();
                    Bundle parcelableBundle3 = null;
        
                    if (result3 != 0)
                    {
                        parcelableBundle3 = (Bundle)Bundle_CREATOR.createFromParcel(dataInput);
                    }
        
                    service.B6(parcelableBundle3);
                    replyOutput.writeNoException();
                    return true;
        
                case 5:
                    dataInput.enforceInterface(interfaceDescriptor);
                    int result4 = dataInput.readInt();
                    int methodId2 = dataInput.readInt();
                    Uri parcelableUri = null;
        
                    if (methodId2 != 0)
                    {
                        parcelableUri = (Uri)Uri_CREATOR.createFromParcel(dataInput);
                    }
        
                    int argInt2 = dataInput.readInt();
                    Bundle parcelableBundle4 = null;
        
                    if (argInt2 != 0)
                    {
                        parcelableBundle4 = (Bundle)Bundle_CREATOR.createFromParcel(dataInput);
                    }
        
                    service.J6(result4, parcelableUri, methodId2 != 0, parcelableBundle4);
                    replyOutput.writeNoException();
                    return true;
        
                case 0x5f4e5446:
                    dataInput.enforceInterface(interfaceDescriptor);
                    string interfaceName2 = dataInput.readString();
                    int result5 = dataInput.readInt();
                    Bundle parcelableBundle5 = null;
        
                    if (result5 != 0)
                    {
                        parcelableBundle5 = (Bundle)Bundle_CREATOR.createFromParcel(dataInput);
                    }
        
                    service.q6(interfaceName2, parcelableBundle5);
                    replyOutput.writeString(interfaceDescriptor);
                    return true;
        
                default:
                    return super.onTransact(service, requestId, dataInput, replyOutput, flags);
            }
        }

        // Original: a$a
        public class CustomTabsCallbackBinder : Binder, ICustomTabsCallback
        {
            public CustomTabsCallbackBinder()
            {
                AttachInterface(this, "android.support.customtabs.ICustomTabsCallback");
            }
        }

        // Original: asBinder
        public static IBinder asBinder(b_a_a service) { return service.binder; }

        // Original: q1
        public static bool Q1(b_a_a service, a requestId, Uri dataInput, Bundle replyOutput, List flags)
        {
            Parcel exception = Parcel.Obtain();
            Parcel replyParcel = Parcel.Obtain();
        
            try
            {
                exception.WriteInterfaceToken("android.support.customtabs.ICustomTabsService");
        
                IBinder binder;
                if (requestId == null)
                    binder = null;
                else
                    binder = requestId.AsBinder();
        
                exception.WriteStrongBinder(binder);
        
                if (dataInput == null)
                    exception.WriteInt(0);
                else
                {
                    exception.WriteInt(1);
                    dataInput.WriteToParcel(exception, 0);
                }
        
                if (replyOutput == null)
                    exception.WriteInt(0);
                else
                {
                    exception.WriteInt(1);
                    replyOutput.WriteToParcel(exception, 0);
                }
        
                exception.WriteTypedList(flags);
        
                IBinder serviceBinder = service.binder;
                serviceBinder.Transact(4, exception, replyParcel, 0);
        
                replyParcel.ReadException();
                int result = replyParcel.ReadInt();
                return result != 0;
            }
            finally
            {
                replyParcel.Recycle();
                exception.Recycle();
            }
        }

        // Original: x4
        public static bool x4(b_a_a service, a requestId)
        {
            Parcel exception = Parcel.obtain();
            Parcel replyParcel = Parcel.obtain();
        
            try
            {
                exception.writeInterfaceToken("android.support.customtabs.ICustomTabsService");
        
                IBinder binder;
                if (requestId == null)
                {
                    binder = null;
                }
                else
                {
                    binder = requestId.asBinder();
                }
        
                exception.writeStrongBinder(binder);
        
                binder = service.binder;
                binder.transact(3, exception, replyParcel, 0);
                replyParcel.readException();
        
                return replyParcel.readInt() != 0;
            }
            finally
            {
                replyParcel.recycle();
                exception.recycle();
            }
        }

        // Original: p3
        public static bool replyOutput(b_a_a service, long requestId)
        {
            Parcel exception = Parcel.obtain();
            Parcel replyParcel = Parcel.obtain();
        
            try
            {
                exception.writeInterfaceToken("android.support.customtabs.ICustomTabsService");
                exception.writeLong(requestId);
                IBinder ref_01 = service.binder;
                ref_01.transact(2, exception, replyParcel, 0);
                replyParcel.readException();
                int result = replyParcel.readInt();
                return result != 0;
            }
            finally
            {
                replyParcel.recycle();
                exception.recycle();
            }
        }

    }
}
