// utilities_9.c
// Auto-generated by Refactory Pipeline

#include "utilities_9.h"


// launch
void launch(ActivityResultLauncher *listener, Object *activityResultRegistry) {
    (*listener->launch)(listener, activityResultRegistry, (ActivityOptionsCompat *)0x0);
}



// ActivityResultRegistry$1
void androidx::activity::result::ActivityResultRegistry$1::ActivityResultRegistry_1(ActivityResultRegistry_1 *listener, ActivityResultRegistry *activityResultRegistry, String *key, ActivityResultCallback *requestCode, ActivityResultContract *contract) {
    listener->listener$0 = activityResultRegistry;
    listener->key = key;
    listener->callback = requestCode;
    listener->contract = contract;
    (*listener-><init>)(listener);
}


// onStateChanged
void androidx::activity::result::ActivityResultRegistry$1::onStateChanged(ActivityResultRegistry_1 *listener, LifecycleOwner *activityResultRegistry, Lifecycle_Event *key) {
  boolean bVar1;
  Parcelable *ref;
  int iVar2;
  Intent *pIVar3;
  Object *pOVar4;
  ActivityResultContract *ref_00;
  Map *resultsMap;
  Bundle *resultBundle;
  ActivityResultRegistry *activityResultRegistry;
  Object *callbackEntry;
  ActivityResultCallback *pAVar9;

  if (key->equals(Lifecycle_Event_ON_START)) {
    resultsMap = listener->listener$0->keyToCallback;
    callbackEntry = listener->key;
    pOVar4 = new Object(listener->callback, listener->contract);
    resultsMap->put(callbackEntry, pOVar4);

    if (resultsMap->containsKey(listener->key)) {
      pOVar4 = resultsMap->get(listener->key);
      resultsMap->remove(listener->key);
      pAVar9 = listener->callback;
      pAVar9->onActivityResult(pOVar4);
    }

    resultBundle = listener->listener$0->pendingResults;
    ref = resultBundle->getParcelable(listener->key);
    checkCast(ref, ActivityResult);

    if (ref != nullptr) {
      resultBundle->remove(listener->key);
      pAVar9 = listener->callback;
      ref_00 = listener->contract;
      iVar2 = ref->getResultCode();
      pIVar3 = ref->getData();
      pOVar4 = ref_00->parseResult(iVar2, pIVar3);
      pAVar9->onActivityResult(pOVar4);
    }
  } else if (key->equals(Lifecycle_Event_ON_STOP)) {
    resultsMap = listener->listener$0->keyToCallback;
    resultsMap->remove(listener->key);
  } else if (key->equals(Lifecycle_Event_ON_DESTROY)) {
    activityResultRegistry = listener->listener$0;
    activityResultRegistry->unregister(listener->key);
  }
}


// ActivityResultRegistry$2
void androidx::activity::result::ActivityResultRegistry$2::ActivityResultRegistry_2(ActivityResultRegistry_2 *listener, ActivityResultRegistry *activityResultRegistry, String *key, int requestCode, ActivityResultContract *contract) {
  listener->listener$0 = activityResultRegistry;
  listener->key = key;
  listener->val$requestCode = requestCode;
  listener->contract = contract;
  listener->ActivityResultLauncher(listener);
}

