// utilities_5.c
// Auto-generated by Refactory Pipeline

#include "utilities_5.h"


// getSavedStateRegistry
SavedStateRegistry* android::activity::ComponentActivity::getSavedStateRegistry(ComponentActivity *componentActivity) {
    SavedStateRegistryController *contextAwareHelper = *componentActivity->savedStateRegistryController;
    return (*contextAwareHelper->getSavedStateRegistry)(contextAwareHelper);
}


// getLastCustomNonConfigurationInstance
Object* androidx::activity::ComponentActivity::getLastCustomNonConfigurationInstance(ComponentActivity* componentActivity) {
  Object* nonConfigurationInstance;

  nonConfigurationInstance = (*componentActivity->getLastNonConfigurationInstance)(componentActivity);
  checkCast(nonConfigurationInstance, ComponentActivity_NonConfigurationInstances);

  if (nonConfigurationInstance != nullptr) {
    nonConfigurationInstance = *nonConfigurationInstance->custom;
  } else {
    nonConfigurationInstance = nullptr;
  }

  return nonConfigurationInstance;
}


// onRetainNonConfigurationInstance
Object* androidx::activity::ComponentActivity::onRetainNonConfigurationInstance(ComponentActivity* componentActivity) {
    Object* nonConfigurationInstance = (*componentActivity->onRetainCustomNonConfigurationInstance)(componentActivity);
    ViewModelStore* viewModelStore = *componentActivity->viewModelStore;

    if (viewModelStore == nullptr) {
        Object* nonConfigInstance = (*componentActivity->getLastNonConfigurationInstance)(componentActivity);
        checkCast(nonConfigInstance, ComponentActivity_NonConfigurationInstances);

        if (nonConfigInstance != nullptr) {
            viewModelStore = *nonConfigInstance->viewModelStore;
        }
    }

    if (viewModelStore == nullptr && nonConfigurationInstance == nullptr) {
        return nullptr;
    }

    ComponentActivity$NonConfigurationInstances* ncis = new ComponentActivity$NonConfigurationInstances();
    *ncis->custom = nonConfigurationInstance;
    *ncis->viewModelStore = viewModelStore;

    return ncis;
}


// ComponentActivity
void androidx::activity::ComponentActivity::ComponentActivity(ComponentActivity *componentActivity, ActivityResultContract* listener) {
  (*componentActivity->ComponentActivity)(componentActivity);
  componentActivity->mContentLayoutId = listener;
}


// addContentView
void androidx::activity::ComponentActivity::addContentView(ComponentActivity *componentActivity, View *listener, ViewGroup_LayoutParams *layoutParams) {
  (*componentActivity->initViewTreeOwners)(componentActivity);
  (*super->addContentView)(componentActivity, listener, layoutParams);
}


// addOnContextAvailableListener
void androidx::activity::ComponentActivity::addOnContextAvailableListener(ComponentActivity *componentActivity, OnContextAvailableListener *listener) {
    ContextAwareHelper *contextAwareHelper = *componentActivity->contextAwareHelper;
    (*contextAwareHelper->addOnContextAvailableListener)(contextAwareHelper, listener);
}


// ensureViewModelStore
void androidx::activity::ComponentActivity::ensureViewModelStore(ComponentActivity *componentActivity)
{
  Object *nonConfigurationInstance;
  ViewModelStore *viewModelStore;

  if (*componentActivity->viewModelStore == (ViewModelStore *)0x0) {
    nonConfigurationInstance = (*componentActivity->getLastNonConfigurationInstance)(componentActivity);
    checkCast(nonConfigurationInstance, ComponentActivity_NonConfigurationInstances);

    if (nonConfigurationInstance != (Object *)0x0) {
      *componentActivity->viewModelStore = *nonConfigurationInstance->viewModelStore;
    }

    if (*componentActivity->viewModelStore == (ViewModelStore *)0x0) {
      viewModelStore = new ViewModelStore();
      *componentActivity->viewModelStore = viewModelStore;
    }
  }
}



// initViewTreeOwners
void androidx::activity::ComponentActivity::initViewTreeOwners(ComponentActivity *componentActivity) {
  Window *window = (*componentActivity->getWindow)(componentActivity);
  View *decorView = (*window->getDecorView)(window);

  (*ViewTreeLifecycleOwner_set)(decorView, componentActivity);
  (*ViewTreeViewModelStoreOwner_set)(decorView, componentActivity);
  (*ViewTreeSavedStateRegistryOwner_set)(decorView, componentActivity);
}

