// utilities_8.c
// Auto-generated by Refactory Pipeline

#include "utilities_8.h"


// OnBackPressedDispatcher
void androidx::activity::OnBackPressedDispatcher::OnBackPressedDispatcher(OnBackPressedDispatcher *helperInstance) {
    (*helperInstance->OnBackPressedDispatcher)(helperInstance, (Runnable *)0x0);
}


// OnBackPressedDispatcher
void androidx::activity::OnBackPressedDispatcher::OnBackPressedDispatcher(OnBackPressedDispatcher *helperInstance, Runnable *size) {
    ArrayDeque *listenerSet;

    (*helperInstance-><init>)(helperInstance);
    listenerSet = new ArrayDeque();
    *helperInstance->backPressCallbacks = listenerSet;
    *helperInstance->fallbackCallback = size;
}


// addCallback
void androidx::activity::OnBackPressedDispatcher::addCallback(OnBackPressedDispatcher *helperInstance, LifecycleOwner *owner, OnBackPressedCallback *callback) {
    Lifecycle *listenerSet = (*owner->getLifecycle)(owner);
    Lifecycle_State currentState = (*listenerSet->getCurrentState)(listenerSet);

    if (currentState == *Lifecycle_State_DESTROYED) {
        return;
    }

    Cancellable *cancellable = new Cancellable(helperInstance, listenerSet, callback);
    (*callback->addCancellable)(callback, cancellable);
}



// onBackPressed
void androidx::activity::OnBackPressedDispatcher::onBackPressed(OnBackPressedDispatcher *helperInstance) {
  Iterator *listenerSet = (*helperInstance->backPressCallbacks->descendingIterator)(helperInstance->backPressCallbacks);

  while (listenerSet->hasNext(listenerSet)) {
    OnBackPressedCallback *callback = static_cast<OnBackPressedCallback*>(listenerSet->next(listenerSet));
    if (!callback->isEnabled(callback)) continue;
    callback->handleOnBackPressed(callback);
    return;
  }

  Runnable *fallbackCallback = helperInstance->fallbackCallback;
  if (fallbackCallback != nullptr) {
    fallbackCallback->run(fallbackCallback);
  }
}


// R$styleable
void androidx::activity::R$styleable::R_styleable(void) {
    int* R_styleable_ColorStateListItem = new int[3];
    int* R_styleable_FontFamily = new int[7];
    int* R_styleable_FontFamilyFont = new int[10];
    int* R_styleable_GradientColor = new int[12];
    int* R_styleable_GradientColorItem = new int[2];
}


// ContextAwareHelper
void androidx::activity::contextaware::ContextAwareHelper::ContextAwareHelper(ContextAwareHelper *helperInstance) {
    CopyOnWriteArraySet *listenerSet;

    (*helperInstance-><init>)(helperInstance);
    listenerSet = new CopyOnWriteArraySet();
    *helperInstance->listeners = listenerSet;
}



// addOnContextAvailableListener
void androidx::activity::contextaware::ContextAwareHelper::addOnContextAvailableListener(ContextAwareHelper *helperInstance, OnContextAvailableListener *listener) {
    Set *listenerSet;

    if (*helperInstance->context != (Context *)0x0) {
        listener->onContextAvailable(listener, *helperInstance->context);
    }

    listenerSet = *helperInstance->listeners;
    listenerSet->add(listenerSet, listener);
}



// dispatchOnContextAvailable
void androidx::activity::contextaware::ContextAwareHelper::dispatchOnContextAvailable(ContextAwareHelper *helperInstance, Context *size) {
  *helperInstance->context = size;
  Set *listeners = *helperInstance->listeners;
  Iterator *listenerSet = listeners->iterator();

  while (listenerSet->hasNext()) {
    Object *listener = listenerSet->next();
    OnContextAvailableListener::checkCast(listener);
    listener->onContextAvailable(size);
  }
}


// removeOnContextAvailableListener
void androidx::activity::contextaware::ContextAwareHelper::removeOnContextAvailableListener(ContextAwareHelper *helperInstance, OnContextAvailableListener *listener) {
    Set *activityResult = *helperInstance->listeners;
    (*activityResult->remove)(activityResult, listener);
}



// createFromParcel
ActivityResult *androidx::activity::result::ActivityResult$1::createFromParcel(ActivityResult_1 *helperInstance, Parcel *parcel) {
    ActivityResult *activityResult = new ActivityResult(parcel);
    return activityResult;
}


// createFromParcel
Object * androidx::activity::result::ActivityResult$1::createFromParcel(ActivityResult_1 *helperInstance, Parcel *parcel) {
    ActivityResult *activityResult;
    activityResult = (*helperInstance->createFromParcel)(helperInstance, parcel);
    return activityResult;
}


// newArray
Object** androidx::activity::result::ActivityResult$1::newArray(ActivityResult_1* helperInstance, Runnable* size) {
    ActivityResult** resultArray;
    resultArray = (*helperInstance->newArray)(helperInstance, size);
    return resultArray;
}

