// utilities_3.h
// Auto-generated by Refactory Pipeline

#ifndef UTILITIES_3_H
#define UTILITIES_3_H

#include <stdint.h>
#include <stdlib.h>

// Discovered Structs
typedef struct ComponentActivity_1 { ComponentActivity *this$0; } ComponentActivity_1;

typedef struct ComponentActivity_2 { ComponentActivity *this$0; } ComponentActivity_2;

typedef struct ComponentActivity_2_1 { ComponentActivity_2 *this$1; int val$requestCode; ActivityResultContract_SynchronousResult *val$synchronousResult; } ComponentActivity_2_1;

typedef struct ComponentActivity_2_2 { ComponentActivity_2 *this$1; int val$requestCode; IntentSender_SendIntentException *val$e; } ComponentActivity_2_2;

typedef struct ResultReceiver_MyResultReceiver { ResultReceiver *outerInstance; } ResultReceiver_MyResultReceiver;

void android::support::v4::os::ResultReceiver::ResultReceiver(ResultReceiver *instance, Handler *requestCode);
void android::support::v4::os::ResultReceiver::ResultReceiver(ResultReceiver *instance, Parcel *requestCode);
void android::support::v4::os::ResultReceiver::send(ResultReceiver *instance, int requestCode, Bundle *activityResultContract);
void android::support::v4::os::ResultReceiver::writeToParcel(ResultReceiver *instance, Parcel *requestCode, int activityResultContract);
void androidx::activity::ComponentActivity$1::ComponentActivity_1(ComponentActivity_1 *instance, ComponentActivity *requestCode);
void androidx::activity::ComponentActivity$2$1::ComponentActivity_2_1(ComponentActivity_2_1 *instance, ComponentActivity_2 *requestCode, int activityResultContract, ActivityResultContract_SynchronousResult *input);
void androidx::activity::ComponentActivity$2$1::run(ComponentActivity_2_1 *instance);
void androidx::activity::ComponentActivity$2::ComponentActivity_2(ComponentActivity_2 *instance, ComponentActivity *requestCode);

#endif // UTILITIES_3_H
