// utilities_5.h
// Auto-generated by Refactory Pipeline

#ifndef UTILITIES_5_H
#define UTILITIES_5_H

#include <stdint.h>
#include <stdlib.h>

// Discovered Structs
typedef struct OnBackPressedDispatcher { /* ... */ } OnBackPressedDispatcher;

typedef struct ComponentActivity_NonConfigurationInstances { Object* custom; ViewModelStore* viewModelStore; } ComponentActivity_NonConfigurationInstances;

typedef struct ViewModelProvider_Factory { /* ... */ } ViewModelProvider_Factory;

typedef struct ViewModelStore { /* ... */ } ViewModelStore;

typedef struct SavedStateRegistryController { /* ... */ } SavedStateRegistryController;

typedef struct ActivityResultContract { /* ... */ } ActivityResultContract;

typedef struct ActivityResultCallback { /* ... */ } ActivityResultCallback;

typedef struct Intent { /* ... */ } Intent;

typedef struct Bundle { /* ... */ } Bundle;

typedef struct Application { /* ... */ } Application;

typedef struct ContextAwareHelper { /* ... */ } ContextAwareHelper;

typedef struct LifecycleRegistry { /* ... */ } LifecycleRegistry;

SavedStateRegistry* android::activity::ComponentActivity::getSavedStateRegistry(ComponentActivity *componentActivity);
Object* androidx::activity::ComponentActivity::getLastCustomNonConfigurationInstance(ComponentActivity* componentActivity);
Object* androidx::activity::ComponentActivity::onRetainNonConfigurationInstance(ComponentActivity* componentActivity);
void androidx::activity::ComponentActivity::ComponentActivity(ComponentActivity *componentActivity, ActivityResultContract* listener);
void androidx::activity::ComponentActivity::addContentView(ComponentActivity *componentActivity, View *listener, ViewGroup_LayoutParams *layoutParams);
void androidx::activity::ComponentActivity::addOnContextAvailableListener(ComponentActivity *componentActivity, OnContextAvailableListener *listener);
if (*componentActivity->viewModelStore == (ViewModelStore *)0x0);
void androidx::activity::ComponentActivity::initViewTreeOwners(ComponentActivity *componentActivity);

#endif // UTILITIES_5_H
