// utilities_2.h
// Auto-generated by Refactory Pipeline

#ifndef UTILITIES_2_H
#define UTILITIES_2_H

#include <stdint.h>
#include <stdlib.h>

// Discovered Structs
typedef struct IInterface { void (*queryLocalInterface)(IBinder*, String*); } IInterface;

typedef struct IBinder { void (*enforceInterface)(Parcel*, String*); int (*readInt)(Parcel*); } IBinder;

typedef struct Parcel { void (*writeString)(Parcel*, String*); } Parcel;

typedef struct Handler { void (*post)(Handler*, Runnable*); } Handler;

typedef struct Runnable { void (*run)(Runnable*); } Runnable;

typedef struct ResultReceiver { IResultReceiver_Stub* stub; int resultCode; Bundle* resultData; Handler* handler; } ResultReceiver;

typedef struct IResultReceiver_Stub { void (*<init>)(IResultReceiver_Stub*); void (*attachInterface)(IResultReceiver_Stub*, IResultReceiver*, String*); boolean (*onTransact)(IResultReceiver_Stub*, int, Parcel*, Parcel*, int); } IResultReceiver_Stub;

typedef struct IResultReceiver_Stub_Proxy { IResultReceiver_Stub stub; IBinder* binder; } IResultReceiver_Stub_Proxy;

typedef struct ResultReceiver_1 { void (*createFromParcel)(ResultReceiver_1*, Parcel*); } ResultReceiver_1;

typedef struct ResultReceiver_MyRunnable { ResultReceiver* this$0; int resultCode; Bundle* resultData; } ResultReceiver_MyRunnable;

bool android::support::v4::os::IResultReceiver$Stub::setDefaultImpl(IResultReceiver* receiver);
ResultReceiver* android::support::v4::os::ResultReceiver$1::createFromParcel(ResultReceiver_1* receiver, Parcel* parcel);
Object* android::support::v4::os::ResultReceiver$1::createFromParcel(ResultReceiver_1* receiver, Parcel* parcel);
Object** android::support::v4::os::ResultReceiver$1::newArray(ResultReceiver_1* receiver, int size);
void android::support::v4::os::ResultReceiver$MyResultReceiver::ResultReceiver_MyResultReceiver(ResultReceiver_MyResultReceiver *receiver, ResultReceiver *resultReceiver);
void android::support::v4::os::ResultReceiver$MyResultReceiver::send(ResultReceiver_MyResultReceiver *receiver, int receiver, Bundle *resultCode);
void android::support::v4::os::ResultReceiver$MyRunnable::ResultReceiver_MyRunnable(ResultReceiver_MyRunnable *receiver, ResultReceiver *receiver, Parcel* resultCode, Bundle *resultData);
void android::support::v4::os::ResultReceiver$MyRunnable::run(ResultReceiver_MyRunnable *receiver);
void android::support::v4::os::ResultReceiver::ResultReceiver(void);

#endif // UTILITIES_2_H
