// utilities_8.h
// Auto-generated by Refactory Pipeline

#ifndef UTILITIES_8_H
#define UTILITIES_8_H

#include <stdint.h>
#include <stdlib.h>

// Discovered Structs
typedef struct OnBackPressedDispatcher { ArrayDeque *mOnBackPressedCallbacks; Runnable *mFallbackOnBackPressed; } OnBackPressedDispatcher;

typedef struct ContextAwareHelper { CopyOnWriteArraySet *mListeners; Context *mContext; } ContextAwareHelper;

typedef struct ActivityResult { /* fields */ } ActivityResult;

void androidx::activity::OnBackPressedDispatcher::OnBackPressedDispatcher(OnBackPressedDispatcher *helperInstance);
void androidx::activity::OnBackPressedDispatcher::OnBackPressedDispatcher(OnBackPressedDispatcher *helperInstance, Runnable *size);
void androidx::activity::OnBackPressedDispatcher::addCallback(OnBackPressedDispatcher *helperInstance, LifecycleOwner *owner, OnBackPressedCallback *callback);
void androidx::activity::OnBackPressedDispatcher::onBackPressed(OnBackPressedDispatcher *helperInstance);
void androidx::activity::R$styleable::R_styleable(void);
void androidx::activity::contextaware::ContextAwareHelper::ContextAwareHelper(ContextAwareHelper *helperInstance);
void androidx::activity::contextaware::ContextAwareHelper::addOnContextAvailableListener(ContextAwareHelper *helperInstance, OnContextAvailableListener *listener);
void androidx::activity::contextaware::ContextAwareHelper::dispatchOnContextAvailable(ContextAwareHelper *helperInstance, Context *size);
void androidx::activity::contextaware::ContextAwareHelper::removeOnContextAvailableListener(ContextAwareHelper *helperInstance, OnContextAvailableListener *listener);
ActivityResult *androidx::activity::result::ActivityResult$1::createFromParcel(ActivityResult_1 *helperInstance, Parcel *parcel);
Object * androidx::activity::result::ActivityResult$1::createFromParcel(ActivityResult_1 *helperInstance, Parcel *parcel);
Object** androidx::activity::result::ActivityResult$1::newArray(ActivityResult_1* helperInstance, Runnable* size);

#endif // UTILITIES_8_H
