// utilities_1.h
// Auto-generated by Refactory Pipeline

#ifndef UTILITIES_1_H
#define UTILITIES_1_H

#include <stdint.h>
#include <stdlib.h>

// Discovered Structs
typedef struct INotificationSideChannel_Stub_Proxy { IBinder *mRemote; } INotificationSideChannel_Stub_Proxy;

typedef struct Notification { /* fields */ } Notification;

void android::support::v4::app::INotificationSideChannel$Stub$Proxy::INotificationSideChannel_Stub_Proxy(INotificationSideChannel_Stub_Proxy *proxyInstance, IBinder *resultCode);
INotificationSideChannel *android::support::v4::app::INotificationSideChannel$Stub::asInterface(IBinder *parcel);
bool android::support::v4::app::INotificationSideChannel$Stub::setDefaultImpl(INotificationSideChannel *parcel);
IconCompat *android::support::v4::graphics::drawable::IconCompatParcelizer::read(VersionedParcel *parcel);
void android::support::v4::os::IResultReceiver$Stub$Proxy::IResultReceiver_Stub_Proxy(IResultReceiver_Stub_Proxy* proxyInstance, IBinder* resultCode);
void android::support::v4::os::IResultReceiver$Stub$Proxy::send(IResultReceiver_Stub_Proxy *proxyInstance, IBinder* resultCode, Bundle *data);

#endif // UTILITIES_1_H
