// utilities_9.h
// Auto-generated by Refactory Pipeline

#ifndef UTILITIES_9_H
#define UTILITIES_9_H

#include <stdint.h>
#include <stdlib.h>

// Discovered Structs
typedef struct ActivityResultLauncher { void (*launch)(void*, Object*, ActivityOptionsCompat*); } ActivityResultLauncher;

typedef struct ActivityResultRegistry$1 { ActivityResultRegistry* this$0; java::lang::String* val$key; ActivityResultCallback* val$callback; ActivityResultContract* val$contract; } ActivityResultRegistry$1;

typedef struct LifecycleEventObserver { void (*onStateChanged)(void*, LifecycleOwner*, Lifecycle_Event*); } LifecycleEventObserver;

typedef struct ActivityResultRegistry$2 { ActivityResultRegistry* this$0; java::lang::String* val$key; int val$requestCode; ActivityResultContract* val$contract; } ActivityResultRegistry$2;

typedef struct ActivityResultCallback { void (*onActivityResult)(void*, Object*); } ActivityResultCallback;

typedef struct ActivityResultContract { Object* (*parseResult)(void*, int, Intent*); } ActivityResultContract;

typedef struct ActivityResultRegistry$PendingResults { Object* (*getParcelable)(void*, java::lang::String*); void (*remove)(void*, java::lang::String*); void (*put)(void*, java::lang::String*, Object*); } ActivityResultRegistry$PendingResults;

typedef struct LifecycleOwner { void (*addObserver)(void*, LifecycleEventObserver*); } LifecycleOwner;

typedef struct Lifecycle_Event { boolean (*equals)(void*, void*); } Lifecycle_Event;

void launch(ActivityResultLauncher *listener, Object *activityResultRegistry);
void androidx::activity::result::ActivityResultRegistry$1::ActivityResultRegistry_1(ActivityResultRegistry_1 *listener, ActivityResultRegistry *activityResultRegistry, String *key, ActivityResultCallback *requestCode, ActivityResultContract *contract);
void androidx::activity::result::ActivityResultRegistry$1::onStateChanged(ActivityResultRegistry_1 *listener, LifecycleOwner *activityResultRegistry, Lifecycle_Event *key);
void androidx::activity::result::ActivityResultRegistry$2::ActivityResultRegistry_2(ActivityResultRegistry_2 *listener, ActivityResultRegistry *activityResultRegistry, String *key, int requestCode, ActivityResultContract *contract);

#endif // UTILITIES_9_H
