// utilities_6.h
// Auto-generated by Refactory Pipeline

#ifndef UTILITIES_6_H
#define UTILITIES_6_H

#include <stdint.h>
#include <stdlib.h>

// Discovered Structs
typedef struct ActivityResultRegistry { void (*dispatchResult)(ActivityResultRegistry*, int, int, Intent*); } ActivityResultRegistry;

typedef struct Lifecycle { void (*setCurrentState)(Lifecycle*, int); } Lifecycle;

typedef struct LifecycleRegistry { int currentState; } LifecycleRegistry;

typedef struct SavedStateRegistryController { void (*performSave)(SavedStateRegistryController*, Bundle*); } SavedStateRegistryController;

if (!isTracingEnabled);
void androidx::activity::ComponentActivity::onBackPressed(ComponentActivity *self);
void androidx::activity::ComponentActivity::onRequestPermissionsResult(ComponentActivity *self, int activity, String **layoutParams, int *grantResults);
void androidx::activity::ComponentActivity::onSaveInstanceState(ComponentActivity *self, Bundle *activity);
void androidx::activity::ComponentActivity::removeOnContextAvailableListener(ComponentActivity *self, OnContextAvailableListener *activity);
void androidx::activity::ComponentActivity::setContentView(ComponentActivity *self, View *activity);
void androidx::activity::ComponentActivity::setContentView(ComponentActivity *self, View *activity, ViewGroup_LayoutParams *layoutParams);
void androidx::activity::ComponentActivity::setContentView(ComponentActivity *self, int activity);
void androidx::activity::ImmLeaksCleaner::ImmLeaksCleaner(ImmLeaksCleaner *self, Activity *activity);

#endif // UTILITIES_6_H
