// utilities_7.h
// Auto-generated by Refactory Pipeline

#ifndef UTILITIES_7_H
#define UTILITIES_7_H

#include <stdint.h>
#include <stdlib.h>

// Discovered Structs
typedef struct Lifecycle_Event { int event_id; } Lifecycle_Event;

typedef struct Field { void *get(void *obj, Object *ref); void set(void *obj, Object *ref, void *value); } Field;

typedef struct CopyOnWriteArrayList { void add(void *list, void *item); bool remove(void *list, void *item); Iterator *iterator(void *list); } CopyOnWriteArrayList;

typedef struct Activity { Object *getSystemService(String *name); } Activity;

typedef struct OnBackPressedCallback { void <init>(); CopyOnWriteArrayList *mCancellables; boolean *mEnabled; } OnBackPressedCallback;

typedef struct Cancellable { void cancel(); } Cancellable;

typedef struct Lifecycle { void addObserver(LifecycleEventObserver *observer); void removeObserver(LifecycleEventObserver *observer); } Lifecycle;

typedef struct Iterator { bool hasNext(); void *next(); } Iterator;

typedef struct OnBackPressedDispatcher_LifecycleOnBackPressedCancellable { OnBackPressedDispatcher *this$0; Lifecycle *mLifecycle; OnBackPressedCallback *mOnBackPressedCallback; Cancellable *mCurrentCancellable; void <init>(OnBackPressedDispatcher *this$0, Lifecycle *lifecycle, OnBackPressedCallback *callback); void cancel(); void onStateChanged(LifecycleOwner *owner, Lifecycle_Event *event); } OnBackPressedDispatcher_LifecycleOnBackPressedCancellable;

typedef struct OnBackPressedDispatcher_OnBackPressedCancellable { OnBackPressedDispatcher *this$0; OnBackPressedCallback *mOnBackPressedCallback; void <init>(OnBackPressedDispatcher *this$0, OnBackPressedCallback *callback); } OnBackPressedDispatcher_OnBackPressedCancellable;

void androidx::activity::OnBackPressedCallback::OnBackPressedCallback(OnBackPressedCallback *dispatcher, boolean callback);
void androidx::activity::OnBackPressedCallback::addCancellable(OnBackPressedCallback *dispatcher, Cancellable *callback);
void androidx::activity::OnBackPressedCallback::remove(OnBackPressedCallback *dispatcher);
void androidx::activity::OnBackPressedCallback::removeCancellable(OnBackPressedCallback *dispatcher, Cancellable *callback);
void androidx::activity::OnBackPressedDispatcher$LifecycleOnBackPressedCancellable::OnBackPressedDispatcher_LifecycleOnBackPressedCancellable(OnBackPressedDispatcher_LifecycleOnBackPressedCancellable *dispatcher, OnBackPressedDispatcher *callback, Lifecycle *onBackPressedCallback, OnBackPressedCallback *onBackPressedCallback);
void androidx::activity::OnBackPressedDispatcher$LifecycleOnBackPressedCancellable::cancel(OnBackPressedDispatcher_LifecycleOnBackPressedCancellable *dispatcher);
void androidx::activity::OnBackPressedDispatcher$LifecycleOnBackPressedCancellable::onStateChanged(OnBackPressedDispatcher_LifecycleOnBackPressedCancellable *dispatcher, LifecycleOwner *callback, Lifecycle_Event *onBackPressedCallback);
void androidx::activity::OnBackPressedDispatcher$OnBackPressedCancellable::OnBackPressedDispatcher_OnBackPressedCancellable(OnBackPressedDispatcher_OnBackPressedCancellable *dispatcher, OnBackPressedDispatcher *callback, OnBackPressedCallback *onBackPressedCallback);
void androidx::activity::OnBackPressedDispatcher$OnBackPressedCancellable::cancel(OnBackPressedDispatcher_OnBackPressedCancellable *dispatcher);
Cancellable* androidx::activity::OnBackPressedDispatcher::addCancellable(OnBackPressedDispatcher *dispatcher, OnBackPressedCallback *callback);
boolean androidx::activity::OnBackPressedDispatcher::hasEnabledCallbacks(OnBackPressedDispatcher *dispatcher);

#endif // UTILITIES_7_H
