// utilities_4.h
// Auto-generated by Refactory Pipeline

#ifndef UTILITIES_4_H
#define UTILITIES_4_H

#include <stdint.h>
#include <stdlib.h>

// Discovered Structs
typedef struct ComponentActivity { int x; int y; } ComponentActivity;

typedef struct ActivityResultRegistry { int x; int y; } ActivityResultRegistry;

typedef struct Bundle { int x; int y; } Bundle;

typedef struct ContextAwareHelper { int x; int y; } ContextAwareHelper;

typedef struct Lifecycle_Event { int x; int y; } Lifecycle_Event;

void androidx::activity::ComponentActivity$3::ComponentActivity_3(ComponentActivity_3 *componentActivityInstance, ComponentActivity *activityResultContract);
void androidx::activity::ComponentActivity$3::onStateChanged(ComponentActivity_3 *componentActivityInstance, LifecycleOwner *activityResultContract, Lifecycle_Event *activityResultCallback);
void androidx::activity::ComponentActivity$4::ComponentActivity_4(ComponentActivity_4 *componentActivityInstance, ComponentActivity *activityResultContract);
if (activityResultCallback == *Lifecycle_Event_ON_DESTROY);
void androidx::activity::ComponentActivity$5::ComponentActivity_5(ComponentActivity_5 *componentActivityInstance, ComponentActivity *activityResultContract);
Bundle * androidx::activity::ComponentActivity$6::saveState(ComponentActivity_6 *componentActivityInstance);
void androidx::activity::ComponentActivity$6::ComponentActivity_6(ComponentActivity_6 *componentActivityInstance, ComponentActivity *activityResultContract);
void androidx::activity::ComponentActivity$7::ComponentActivity_7(ComponentActivity_7 *componentActivityInstance, ComponentActivity *activityResultContract);
Context* androidx::activity::ComponentActivity::peekAvailableContext(ComponentActivity* componentActivityInstance);
ActivityResultLauncher *androidx::activity::ComponentActivity::registerForActivityResult(ComponentActivity *componentActivityInstance, ActivityResultContract *activityResultContract, ActivityResultCallback *activityResultCallback);

#endif // UTILITIES_4_H
